/*
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.ui;

import com.google.inject.Injector;
import edilang.ui.internal.EdilangActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EdilangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EdilangActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EdilangActivator activator = EdilangActivator.getInstance();
		return activator != null ? activator.getInjector(EdilangActivator.IO_THLAEGLER_EDIFACT_EDILANG) : null;
	}

}
