/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bill Level Identification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelOneIdentifier <em>Level One Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelTwoIdentifier <em>Level Two Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelThreeIdentifier <em>Level Three Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelFourIdentifier <em>Level Four Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelFiveIdentifier <em>Level Five Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelSixIdentifier <em>Level Six Identifier</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getBillLevelIdentification()
 * @model
 * @generated
 */
public interface BillLevelIdentification extends AbstractEdiFunction
{
  /**
   * Returns the value of the '<em><b>Level One Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level One Identifier</em>' attribute.
   * @see #setLevelOneIdentifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBillLevelIdentification_LevelOneIdentifier()
   * @model
   * @generated
   */
  String getLevelOneIdentifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelOneIdentifier <em>Level One Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level One Identifier</em>' attribute.
   * @see #getLevelOneIdentifier()
   * @generated
   */
  void setLevelOneIdentifier(String value);

  /**
   * Returns the value of the '<em><b>Level Two Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level Two Identifier</em>' attribute.
   * @see #setLevelTwoIdentifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBillLevelIdentification_LevelTwoIdentifier()
   * @model
   * @generated
   */
  String getLevelTwoIdentifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelTwoIdentifier <em>Level Two Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level Two Identifier</em>' attribute.
   * @see #getLevelTwoIdentifier()
   * @generated
   */
  void setLevelTwoIdentifier(String value);

  /**
   * Returns the value of the '<em><b>Level Three Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level Three Identifier</em>' attribute.
   * @see #setLevelThreeIdentifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBillLevelIdentification_LevelThreeIdentifier()
   * @model
   * @generated
   */
  String getLevelThreeIdentifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelThreeIdentifier <em>Level Three Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level Three Identifier</em>' attribute.
   * @see #getLevelThreeIdentifier()
   * @generated
   */
  void setLevelThreeIdentifier(String value);

  /**
   * Returns the value of the '<em><b>Level Four Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level Four Identifier</em>' attribute.
   * @see #setLevelFourIdentifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBillLevelIdentification_LevelFourIdentifier()
   * @model
   * @generated
   */
  String getLevelFourIdentifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelFourIdentifier <em>Level Four Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level Four Identifier</em>' attribute.
   * @see #getLevelFourIdentifier()
   * @generated
   */
  void setLevelFourIdentifier(String value);

  /**
   * Returns the value of the '<em><b>Level Five Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level Five Identifier</em>' attribute.
   * @see #setLevelFiveIdentifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBillLevelIdentification_LevelFiveIdentifier()
   * @model
   * @generated
   */
  String getLevelFiveIdentifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelFiveIdentifier <em>Level Five Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level Five Identifier</em>' attribute.
   * @see #getLevelFiveIdentifier()
   * @generated
   */
  void setLevelFiveIdentifier(String value);

  /**
   * Returns the value of the '<em><b>Level Six Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level Six Identifier</em>' attribute.
   * @see #setLevelSixIdentifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBillLevelIdentification_LevelSixIdentifier()
   * @model
   * @generated
   */
  String getLevelSixIdentifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BillLevelIdentification#getLevelSixIdentifier <em>Level Six Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level Six Identifier</em>' attribute.
   * @see #getLevelSixIdentifier()
   * @generated
   */
  void setLevelSixIdentifier(String value);

} // BillLevelIdentification
