/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Business Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.BusinessFunction#getBusinessFunctionTypeCodeQualifier <em>Business Function Type Code Qualifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.BusinessFunction#getBusinessFunctionCode <em>Business Function Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.BusinessFunction#getCodeListIdentificationCode <em>Code List Identification Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.BusinessFunction#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.BusinessFunction#getBusinessDescription <em>Business Description</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getBusinessFunction()
 * @model
 * @generated
 */
public interface BusinessFunction extends AbstractEdiFunction
{
  /**
   * Returns the value of the '<em><b>Business Function Type Code Qualifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Business Function Type Code Qualifier</em>' attribute.
   * @see #setBusinessFunctionTypeCodeQualifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBusinessFunction_BusinessFunctionTypeCodeQualifier()
   * @model
   * @generated
   */
  String getBusinessFunctionTypeCodeQualifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BusinessFunction#getBusinessFunctionTypeCodeQualifier <em>Business Function Type Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Business Function Type Code Qualifier</em>' attribute.
   * @see #getBusinessFunctionTypeCodeQualifier()
   * @generated
   */
  void setBusinessFunctionTypeCodeQualifier(String value);

  /**
   * Returns the value of the '<em><b>Business Function Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Business Function Code</em>' attribute.
   * @see #setBusinessFunctionCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBusinessFunction_BusinessFunctionCode()
   * @model
   * @generated
   */
  String getBusinessFunctionCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BusinessFunction#getBusinessFunctionCode <em>Business Function Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Business Function Code</em>' attribute.
   * @see #getBusinessFunctionCode()
   * @generated
   */
  void setBusinessFunctionCode(String value);

  /**
   * Returns the value of the '<em><b>Code List Identification Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code List Identification Code</em>' attribute.
   * @see #setCodeListIdentificationCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBusinessFunction_CodeListIdentificationCode()
   * @model
   * @generated
   */
  String getCodeListIdentificationCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BusinessFunction#getCodeListIdentificationCode <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code List Identification Code</em>' attribute.
   * @see #getCodeListIdentificationCode()
   * @generated
   */
  void setCodeListIdentificationCode(String value);

  /**
   * Returns the value of the '<em><b>Code List Responsible Agency Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code List Responsible Agency Code</em>' attribute.
   * @see #setCodeListResponsibleAgencyCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBusinessFunction_CodeListResponsibleAgencyCode()
   * @model
   * @generated
   */
  String getCodeListResponsibleAgencyCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BusinessFunction#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code List Responsible Agency Code</em>' attribute.
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   */
  void setCodeListResponsibleAgencyCode(String value);

  /**
   * Returns the value of the '<em><b>Business Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Business Description</em>' attribute.
   * @see #setBusinessDescription(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getBusinessFunction_BusinessDescription()
   * @model
   * @generated
   */
  String getBusinessDescription();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.BusinessFunction#getBusinessDescription <em>Business Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Business Description</em>' attribute.
   * @see #getBusinessDescription()
   * @generated
   */
  void setBusinessDescription(String value);

} // BusinessFunction
