/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Control</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.Control#getControlTotalTypeCodeQualifier <em>Control Total Type Code Qualifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.Control#getControlTotalValue <em>Control Total Value</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.Control#getMeasurementUnitCode <em>Measurement Unit Code</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getControl()
 * @model
 * @generated
 */
public interface Control extends AbstractEdiFunction
{
  /**
   * Returns the value of the '<em><b>Control Total Type Code Qualifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Control Total Type Code Qualifier</em>' attribute.
   * @see #setControlTotalTypeCodeQualifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getControl_ControlTotalTypeCodeQualifier()
   * @model
   * @generated
   */
  String getControlTotalTypeCodeQualifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.Control#getControlTotalTypeCodeQualifier <em>Control Total Type Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Control Total Type Code Qualifier</em>' attribute.
   * @see #getControlTotalTypeCodeQualifier()
   * @generated
   */
  void setControlTotalTypeCodeQualifier(String value);

  /**
   * Returns the value of the '<em><b>Control Total Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Control Total Value</em>' attribute.
   * @see #setControlTotalValue(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getControl_ControlTotalValue()
   * @model
   * @generated
   */
  String getControlTotalValue();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.Control#getControlTotalValue <em>Control Total Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Control Total Value</em>' attribute.
   * @see #getControlTotalValue()
   * @generated
   */
  void setControlTotalValue(String value);

  /**
   * Returns the value of the '<em><b>Measurement Unit Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Measurement Unit Code</em>' attribute.
   * @see #setMeasurementUnitCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getControl_MeasurementUnitCode()
   * @model
   * @generated
   */
  String getMeasurementUnitCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.Control#getMeasurementUnitCode <em>Measurement Unit Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Measurement Unit Code</em>' attribute.
   * @see #getMeasurementUnitCode()
   * @generated
   */
  void setMeasurementUnitCode(String value);

} // Control
