/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Date Only Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.DateOnlyFunction#getDate <em>Date</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getDateOnlyFunction()
 * @model
 * @generated
 */
public interface DateOnlyFunction extends AbstractEdiFunction
{
  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getDateOnlyFunction_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.DateOnlyFunction#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

} // DateOnlyFunction
