/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.DocumentMessage#getDocumentNameCode <em>Document Name Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.DocumentMessage#getCodeListIdentificationCode <em>Code List Identification Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.DocumentMessage#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.DocumentMessage#getDocumentName <em>Document Name</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getDocumentMessage()
 * @model
 * @generated
 */
public interface DocumentMessage extends AbstractEdiFunction
{
  /**
   * Returns the value of the '<em><b>Document Name Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Document Name Code</em>' attribute.
   * @see #setDocumentNameCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getDocumentMessage_DocumentNameCode()
   * @model
   * @generated
   */
  String getDocumentNameCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.DocumentMessage#getDocumentNameCode <em>Document Name Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Document Name Code</em>' attribute.
   * @see #getDocumentNameCode()
   * @generated
   */
  void setDocumentNameCode(String value);

  /**
   * Returns the value of the '<em><b>Code List Identification Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code List Identification Code</em>' attribute.
   * @see #setCodeListIdentificationCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getDocumentMessage_CodeListIdentificationCode()
   * @model
   * @generated
   */
  String getCodeListIdentificationCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.DocumentMessage#getCodeListIdentificationCode <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code List Identification Code</em>' attribute.
   * @see #getCodeListIdentificationCode()
   * @generated
   */
  void setCodeListIdentificationCode(String value);

  /**
   * Returns the value of the '<em><b>Code List Responsible Agency Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code List Responsible Agency Code</em>' attribute.
   * @see #setCodeListResponsibleAgencyCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getDocumentMessage_CodeListResponsibleAgencyCode()
   * @model
   * @generated
   */
  String getCodeListResponsibleAgencyCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.DocumentMessage#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code List Responsible Agency Code</em>' attribute.
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   */
  void setCodeListResponsibleAgencyCode(String value);

  /**
   * Returns the value of the '<em><b>Document Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Document Name</em>' attribute.
   * @see #setDocumentName(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getDocumentMessage_DocumentName()
   * @model
   * @generated
   */
  String getDocumentName();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.DocumentMessage#getDocumentName <em>Document Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Document Name</em>' attribute.
   * @see #getDocumentName()
   * @generated
   */
  void setDocumentName(String value);

} // DocumentMessage
