/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see io.thlaegler.edifact.edilang.EdilangPackage
 * @generated
 */
public interface EdilangFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EdilangFactory eINSTANCE = io.thlaegler.edifact.edilang.impl.EdilangFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Edi Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Edi Model</em>'.
   * @generated
   */
  EdiModel createEdiModel();

  /**
   * Returns a new object of class '<em>Abstract Edi Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Edi Segment</em>'.
   * @generated
   */
  AbstractEdiSegment createAbstractEdiSegment();

  /**
   * Returns a new object of class '<em>UNA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNA Segment</em>'.
   * @generated
   */
  UNASegment createUNASegment();

  /**
   * Returns a new object of class '<em>UNB Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNB Segment</em>'.
   * @generated
   */
  UNBSegment createUNBSegment();

  /**
   * Returns a new object of class '<em>UNH Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNH Segment</em>'.
   * @generated
   */
  UNHSegment createUNHSegment();

  /**
   * Returns a new object of class '<em>UNG Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNG Segment</em>'.
   * @generated
   */
  UNGSegment createUNGSegment();

  /**
   * Returns a new object of class '<em>ADR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ADR Segment</em>'.
   * @generated
   */
  ADRSegment createADRSegment();

  /**
   * Returns a new object of class '<em>AGR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AGR Segment</em>'.
   * @generated
   */
  AGRSegment createAGRSegment();

  /**
   * Returns a new object of class '<em>AJT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AJT Segment</em>'.
   * @generated
   */
  AJTSegment createAJTSegment();

  /**
   * Returns a new object of class '<em>ALC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ALC Segment</em>'.
   * @generated
   */
  ALCSegment createALCSegment();

  /**
   * Returns a new object of class '<em>ALI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ALI Segment</em>'.
   * @generated
   */
  ALISegment createALISegment();

  /**
   * Returns a new object of class '<em>APP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>APP Segment</em>'.
   * @generated
   */
  APPSegment createAPPSegment();

  /**
   * Returns a new object of class '<em>APR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>APR Segment</em>'.
   * @generated
   */
  APRSegment createAPRSegment();

  /**
   * Returns a new object of class '<em>ARD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ARD Segment</em>'.
   * @generated
   */
  ARDSegment createARDSegment();

  /**
   * Returns a new object of class '<em>ARR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ARR Segment</em>'.
   * @generated
   */
  ARRSegment createARRSegment();

  /**
   * Returns a new object of class '<em>ASI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ASI Segment</em>'.
   * @generated
   */
  ASISegment createASISegment();

  /**
   * Returns a new object of class '<em>ATT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ATT Segment</em>'.
   * @generated
   */
  ATTSegment createATTSegment();

  /**
   * Returns a new object of class '<em>AUT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AUT Segment</em>'.
   * @generated
   */
  AUTSegment createAUTSegment();

  /**
   * Returns a new object of class '<em>BAS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BAS Segment</em>'.
   * @generated
   */
  BASSegment createBASSegment();

  /**
   * Returns a new object of class '<em>BII Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BII Segment</em>'.
   * @generated
   */
  BIISegment createBIISegment();

  /**
   * Returns a new object of class '<em>BUS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BUS Segment</em>'.
   * @generated
   */
  BUSSegment createBUSSegment();

  /**
   * Returns a new object of class '<em>CAV Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CAV Segment</em>'.
   * @generated
   */
  CAVSegment createCAVSegment();

  /**
   * Returns a new object of class '<em>CCD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CCD Segment</em>'.
   * @generated
   */
  CCDSegment createCCDSegment();

  /**
   * Returns a new object of class '<em>CCI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CCI Segment</em>'.
   * @generated
   */
  CCISegment createCCISegment();

  /**
   * Returns a new object of class '<em>CDI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CDI Segment</em>'.
   * @generated
   */
  CDISegment createCDISegment();

  /**
   * Returns a new object of class '<em>CDS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CDS Segment</em>'.
   * @generated
   */
  CDSSegment createCDSSegment();

  /**
   * Returns a new object of class '<em>CDV Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CDV Segment</em>'.
   * @generated
   */
  CDVSegment createCDVSegment();

  /**
   * Returns a new object of class '<em>CED Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CED Segment</em>'.
   * @generated
   */
  CEDSegment createCEDSegment();

  /**
   * Returns a new object of class '<em>CIN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CIN Segment</em>'.
   * @generated
   */
  CINSegment createCINSegment();

  /**
   * Returns a new object of class '<em>CLA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CLA Segment</em>'.
   * @generated
   */
  CLASegment createCLASegment();

  /**
   * Returns a new object of class '<em>CLI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CLI Segment</em>'.
   * @generated
   */
  CLISegment createCLISegment();

  /**
   * Returns a new object of class '<em>CMP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CMP Segment</em>'.
   * @generated
   */
  CMPSegment createCMPSegment();

  /**
   * Returns a new object of class '<em>CNI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CNI Segment</em>'.
   * @generated
   */
  CNISegment createCNISegment();

  /**
   * Returns a new object of class '<em>COD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>COD Segment</em>'.
   * @generated
   */
  CODSegment createCODSegment();

  /**
   * Returns a new object of class '<em>COM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>COM Segment</em>'.
   * @generated
   */
  COMSegment createCOMSegment();

  /**
   * Returns a new object of class '<em>COT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>COT Segment</em>'.
   * @generated
   */
  COTSegment createCOTSegment();

  /**
   * Returns a new object of class '<em>CPI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CPI Segment</em>'.
   * @generated
   */
  CPISegment createCPISegment();

  /**
   * Returns a new object of class '<em>CPS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CPS Segment</em>'.
   * @generated
   */
  CPSSegment createCPSSegment();

  /**
   * Returns a new object of class '<em>CPT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CPT Segment</em>'.
   * @generated
   */
  CPTSegment createCPTSegment();

  /**
   * Returns a new object of class '<em>CST Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CST Segment</em>'.
   * @generated
   */
  CSTSegment createCSTSegment();

  /**
   * Returns a new object of class '<em>DAM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DAM Segment</em>'.
   * @generated
   */
  DAMSegment createDAMSegment();

  /**
   * Returns a new object of class '<em>DFN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DFN Segment</em>'.
   * @generated
   */
  DFNSegment createDFNSegment();

  /**
   * Returns a new object of class '<em>DGS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DGS Segment</em>'.
   * @generated
   */
  DGSSegment createDGSSegment();

  /**
   * Returns a new object of class '<em>DII Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DII Segment</em>'.
   * @generated
   */
  DIISegment createDIISegment();

  /**
   * Returns a new object of class '<em>DIM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DIM Segment</em>'.
   * @generated
   */
  DIMSegment createDIMSegment();

  /**
   * Returns a new object of class '<em>DLI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DLI Segment</em>'.
   * @generated
   */
  DLISegment createDLISegment();

  /**
   * Returns a new object of class '<em>DLM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DLM Segment</em>'.
   * @generated
   */
  DLMSegment createDLMSegment();

  /**
   * Returns a new object of class '<em>DMS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DMS Segment</em>'.
   * @generated
   */
  DMSSegment createDMSSegment();

  /**
   * Returns a new object of class '<em>DOC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DOC Segment</em>'.
   * @generated
   */
  DOCSegment createDOCSegment();

  /**
   * Returns a new object of class '<em>DRD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DRD Segment</em>'.
   * @generated
   */
  DRDSegment createDRDSegment();

  /**
   * Returns a new object of class '<em>DSG Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DSG Segment</em>'.
   * @generated
   */
  DSGSegment createDSGSegment();

  /**
   * Returns a new object of class '<em>DSI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DSI Segment</em>'.
   * @generated
   */
  DSISegment createDSISegment();

  /**
   * Returns a new object of class '<em>EDT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EDT Segment</em>'.
   * @generated
   */
  EDTSegment createEDTSegment();

  /**
   * Returns a new object of class '<em>EFI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EFI Segment</em>'.
   * @generated
   */
  EFISegment createEFISegment();

  /**
   * Returns a new object of class '<em>ELM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ELM Segment</em>'.
   * @generated
   */
  ELMSegment createELMSegment();

  /**
   * Returns a new object of class '<em>ELU Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ELU Segment</em>'.
   * @generated
   */
  ELUSegment createELUSegment();

  /**
   * Returns a new object of class '<em>ELV Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ELV Segment</em>'.
   * @generated
   */
  ELVSegment createELVSegment();

  /**
   * Returns a new object of class '<em>EMP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EMP Segment</em>'.
   * @generated
   */
  EMPSegment createEMPSegment();

  /**
   * Returns a new object of class '<em>EQA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EQA Segment</em>'.
   * @generated
   */
  EQASegment createEQASegment();

  /**
   * Returns a new object of class '<em>EQD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EQD Segment</em>'.
   * @generated
   */
  EQDSegment createEQDSegment();

  /**
   * Returns a new object of class '<em>EQN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EQN Segment</em>'.
   * @generated
   */
  EQNSegment createEQNSegment();

  /**
   * Returns a new object of class '<em>ERP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ERP Segment</em>'.
   * @generated
   */
  ERPSegment createERPSegment();

  /**
   * Returns a new object of class '<em>EVE Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EVE Segment</em>'.
   * @generated
   */
  EVESegment createEVESegment();

  /**
   * Returns a new object of class '<em>EVT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EVT Segment</em>'.
   * @generated
   */
  EVTSegment createEVTSegment();

  /**
   * Returns a new object of class '<em>FCA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FCA Segment</em>'.
   * @generated
   */
  FCASegment createFCASegment();

  /**
   * Returns a new object of class '<em>FII Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FII Segment</em>'.
   * @generated
   */
  FIISegment createFIISegment();

  /**
   * Returns a new object of class '<em>FNS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FNS Segment</em>'.
   * @generated
   */
  FNSSegment createFNSSegment();

  /**
   * Returns a new object of class '<em>FNT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FNT Segment</em>'.
   * @generated
   */
  FNTSegment createFNTSegment();

  /**
   * Returns a new object of class '<em>FOR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FOR Segment</em>'.
   * @generated
   */
  FORSegment createFORSegment();

  /**
   * Returns a new object of class '<em>FSQ Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FSQ Segment</em>'.
   * @generated
   */
  FSQSegment createFSQSegment();

  /**
   * Returns a new object of class '<em>GDS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GDS Segment</em>'.
   * @generated
   */
  GDSSegment createGDSSegment();

  /**
   * Returns a new object of class '<em>GEI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GEI Segment</em>'.
   * @generated
   */
  GEISegment createGEISegment();

  /**
   * Returns a new object of class '<em>GID Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GID Segment</em>'.
   * @generated
   */
  GIDSegment createGIDSegment();

  /**
   * Returns a new object of class '<em>GIN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GIN Segment</em>'.
   * @generated
   */
  GINSegment createGINSegment();

  /**
   * Returns a new object of class '<em>GIR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GIR Segment</em>'.
   * @generated
   */
  GIRSegment createGIRSegment();

  /**
   * Returns a new object of class '<em>GIS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GIS Segment</em>'.
   * @generated
   */
  GISSegment createGISSegment();

  /**
   * Returns a new object of class '<em>GOR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GOR Segment</em>'.
   * @generated
   */
  GORSegment createGORSegment();

  /**
   * Returns a new object of class '<em>GRU Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GRU Segment</em>'.
   * @generated
   */
  GRUSegment createGRUSegment();

  /**
   * Returns a new object of class '<em>HAN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>HAN Segment</em>'.
   * @generated
   */
  HANSegment createHANSegment();

  /**
   * Returns a new object of class '<em>HYN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>HYN Segment</em>'.
   * @generated
   */
  HYNSegment createHYNSegment();

  /**
   * Returns a new object of class '<em>ICD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ICD Segment</em>'.
   * @generated
   */
  ICDSegment createICDSegment();

  /**
   * Returns a new object of class '<em>IDE Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IDE Segment</em>'.
   * @generated
   */
  IDESegment createIDESegment();

  /**
   * Returns a new object of class '<em>IFD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IFD Segment</em>'.
   * @generated
   */
  IFDSegment createIFDSegment();

  /**
   * Returns a new object of class '<em>IHC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IHC Segment</em>'.
   * @generated
   */
  IHCSegment createIHCSegment();

  /**
   * Returns a new object of class '<em>IMD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IMD Segment</em>'.
   * @generated
   */
  IMDSegment createIMDSegment();

  /**
   * Returns a new object of class '<em>IND Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IND Segment</em>'.
   * @generated
   */
  INDSegment createINDSegment();

  /**
   * Returns a new object of class '<em>INP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>INP Segment</em>'.
   * @generated
   */
  INPSegment createINPSegment();

  /**
   * Returns a new object of class '<em>INV Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>INV Segment</em>'.
   * @generated
   */
  INVSegment createINVSegment();

  /**
   * Returns a new object of class '<em>IRQ Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IRQ Segment</em>'.
   * @generated
   */
  IRQSegment createIRQSegment();

  /**
   * Returns a new object of class '<em>LAN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LAN Segment</em>'.
   * @generated
   */
  LANSegment createLANSegment();

  /**
   * Returns a new object of class '<em>LOC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LOC Segment</em>'.
   * @generated
   */
  LOCSegment createLOCSegment();

  /**
   * Returns a new object of class '<em>MEA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MEA Segment</em>'.
   * @generated
   */
  MEASegment createMEASegment();

  /**
   * Returns a new object of class '<em>MEM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MEM Segment</em>'.
   * @generated
   */
  MEMSegment createMEMSegment();

  /**
   * Returns a new object of class '<em>MKS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MKS Segment</em>'.
   * @generated
   */
  MKSSegment createMKSSegment();

  /**
   * Returns a new object of class '<em>NAT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NAT Segment</em>'.
   * @generated
   */
  NATSegment createNATSegment();

  /**
   * Returns a new object of class '<em>PAC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAC Segment</em>'.
   * @generated
   */
  PACSegment createPACSegment();

  /**
   * Returns a new object of class '<em>PAI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAI Segment</em>'.
   * @generated
   */
  PAISegment createPAISegment();

  /**
   * Returns a new object of class '<em>PAS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAS Segment</em>'.
   * @generated
   */
  PASSegment createPASSegment();

  /**
   * Returns a new object of class '<em>PCC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PCC Segment</em>'.
   * @generated
   */
  PCCSegment createPCCSegment();

  /**
   * Returns a new object of class '<em>PCD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PCD Segment</em>'.
   * @generated
   */
  PCDSegment createPCDSegment();

  /**
   * Returns a new object of class '<em>PER Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PER Segment</em>'.
   * @generated
   */
  PERSegment createPERSegment();

  /**
   * Returns a new object of class '<em>PGI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PGI Segment</em>'.
   * @generated
   */
  PGISegment createPGISegment();

  /**
   * Returns a new object of class '<em>PIA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PIA Segment</em>'.
   * @generated
   */
  PIASegment createPIASegment();

  /**
   * Returns a new object of class '<em>PNA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PNA Segment</em>'.
   * @generated
   */
  PNASegment createPNASegment();

  /**
   * Returns a new object of class '<em>PRC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PRC Segment</em>'.
   * @generated
   */
  PRCSegment createPRCSegment();

  /**
   * Returns a new object of class '<em>PRV Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PRV Segment</em>'.
   * @generated
   */
  PRVSegment createPRVSegment();

  /**
   * Returns a new object of class '<em>PSD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PSD Segment</em>'.
   * @generated
   */
  PSDSegment createPSDSegment();

  /**
   * Returns a new object of class '<em>PTY Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PTY Segment</em>'.
   * @generated
   */
  PTYSegment createPTYSegment();

  /**
   * Returns a new object of class '<em>PYT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PYT Segment</em>'.
   * @generated
   */
  PYTSegment createPYTSegment();

  /**
   * Returns a new object of class '<em>QRS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QRS Segment</em>'.
   * @generated
   */
  QRSSegment createQRSSegment();

  /**
   * Returns a new object of class '<em>QUA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QUA Segment</em>'.
   * @generated
   */
  QUASegment createQUASegment();

  /**
   * Returns a new object of class '<em>QVR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QVR Segment</em>'.
   * @generated
   */
  QVRSegment createQVRSegment();

  /**
   * Returns a new object of class '<em>RCS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RCS Segment</em>'.
   * @generated
   */
  RCSSegment createRCSSegment();

  /**
   * Returns a new object of class '<em>REL Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>REL Segment</em>'.
   * @generated
   */
  RELSegment createRELSegment();

  /**
   * Returns a new object of class '<em>RJL Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RJL Segment</em>'.
   * @generated
   */
  RJLSegment createRJLSegment();

  /**
   * Returns a new object of class '<em>RNG Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RNG Segment</em>'.
   * @generated
   */
  RNGSegment createRNGSegment();

  /**
   * Returns a new object of class '<em>ROD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ROD Segment</em>'.
   * @generated
   */
  RODSegment createRODSegment();

  /**
   * Returns a new object of class '<em>RSL Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RSL Segment</em>'.
   * @generated
   */
  RSLSegment createRSLSegment();

  /**
   * Returns a new object of class '<em>RTE Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RTE Segment</em>'.
   * @generated
   */
  RTESegment createRTESegment();

  /**
   * Returns a new object of class '<em>SAL Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAL Segment</em>'.
   * @generated
   */
  SALSegment createSALSegment();

  /**
   * Returns a new object of class '<em>SCC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SCC Segment</em>'.
   * @generated
   */
  SCCSegment createSCCSegment();

  /**
   * Returns a new object of class '<em>SCD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SCD Segment</em>'.
   * @generated
   */
  SCDSegment createSCDSegment();

  /**
   * Returns a new object of class '<em>SEG Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SEG Segment</em>'.
   * @generated
   */
  SEGSegment createSEGSegment();

  /**
   * Returns a new object of class '<em>SEL Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SEL Segment</em>'.
   * @generated
   */
  SELSegment createSELSegment();

  /**
   * Returns a new object of class '<em>SEQ Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SEQ Segment</em>'.
   * @generated
   */
  SEQSegment createSEQSegment();

  /**
   * Returns a new object of class '<em>SFI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SFI Segment</em>'.
   * @generated
   */
  SFISegment createSFISegment();

  /**
   * Returns a new object of class '<em>SGP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SGP Segment</em>'.
   * @generated
   */
  SGPSegment createSGPSegment();

  /**
   * Returns a new object of class '<em>SGU Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SGU Segment</em>'.
   * @generated
   */
  SGUSegment createSGUSegment();

  /**
   * Returns a new object of class '<em>SPR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SPR Segment</em>'.
   * @generated
   */
  SPRSegment createSPRSegment();

  /**
   * Returns a new object of class '<em>SPS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SPS Segment</em>'.
   * @generated
   */
  SPSSegment createSPSSegment();

  /**
   * Returns a new object of class '<em>STA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>STA Segment</em>'.
   * @generated
   */
  STASegment createSTASegment();

  /**
   * Returns a new object of class '<em>STC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>STC Segment</em>'.
   * @generated
   */
  STCSegment createSTCSegment();

  /**
   * Returns a new object of class '<em>STG Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>STG Segment</em>'.
   * @generated
   */
  STGSegment createSTGSegment();

  /**
   * Returns a new object of class '<em>STS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>STS Segment</em>'.
   * @generated
   */
  STSSegment createSTSSegment();

  /**
   * Returns a new object of class '<em>STX Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>STX Segment</em>'.
   * @generated
   */
  STXSegment createSTXSegment();

  /**
   * Returns a new object of class '<em>TCC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TCC Segment</em>'.
   * @generated
   */
  TCCSegment createTCCSegment();

  /**
   * Returns a new object of class '<em>TDT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TDT Segment</em>'.
   * @generated
   */
  TDTSegment createTDTSegment();

  /**
   * Returns a new object of class '<em>TEM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TEM Segment</em>'.
   * @generated
   */
  TEMSegment createTEMSegment();

  /**
   * Returns a new object of class '<em>TMD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TMD Segment</em>'.
   * @generated
   */
  TMDSegment createTMDSegment();

  /**
   * Returns a new object of class '<em>TMP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TMP Segment</em>'.
   * @generated
   */
  TMPSegment createTMPSegment();

  /**
   * Returns a new object of class '<em>TOD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TOD Segment</em>'.
   * @generated
   */
  TODSegment createTODSegment();

  /**
   * Returns a new object of class '<em>TPL Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TPL Segment</em>'.
   * @generated
   */
  TPLSegment createTPLSegment();

  /**
   * Returns a new object of class '<em>TRU Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TRU Segment</em>'.
   * @generated
   */
  TRUSegment createTRUSegment();

  /**
   * Returns a new object of class '<em>TSR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TSR Segment</em>'.
   * @generated
   */
  TSRSegment createTSRSegment();

  /**
   * Returns a new object of class '<em>VLI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VLI Segment</em>'.
   * @generated
   */
  VLISegment createVLISegment();

  /**
   * Returns a new object of class '<em>MSG Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MSG Segment</em>'.
   * @generated
   */
  MSGSegment createMSGSegment();

  /**
   * Returns a new object of class '<em>POC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>POC Segment</em>'.
   * @generated
   */
  POCSegment createPOCSegment();

  /**
   * Returns a new object of class '<em>UCI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UCI Segment</em>'.
   * @generated
   */
  UCISegment createUCISegment();

  /**
   * Returns a new object of class '<em>PDI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PDI Segment</em>'.
   * @generated
   */
  PDISegment createPDISegment();

  /**
   * Returns a new object of class '<em>RPI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RPI Segment</em>'.
   * @generated
   */
  RPISegment createRPISegment();

  /**
   * Returns a new object of class '<em>MOA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MOA Segment</em>'.
   * @generated
   */
  MOASegment createMOASegment();

  /**
   * Returns a new object of class '<em>LIN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LIN Segment</em>'.
   * @generated
   */
  LINSegment createLINSegment();

  /**
   * Returns a new object of class '<em>PRI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PRI Segment</em>'.
   * @generated
   */
  PRISegment createPRISegment();

  /**
   * Returns a new object of class '<em>QTY Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QTY Segment</em>'.
   * @generated
   */
  QTYSegment createQTYSegment();

  /**
   * Returns a new object of class '<em>CUX Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CUX Segment</em>'.
   * @generated
   */
  CUXSegment createCUXSegment();

  /**
   * Returns a new object of class '<em>TAX Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TAX Segment</em>'.
   * @generated
   */
  TAXSegment createTAXSegment();

  /**
   * Returns a new object of class '<em>RFF Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RFF Segment</em>'.
   * @generated
   */
  RFFSegment createRFFSegment();

  /**
   * Returns a new object of class '<em>NAD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NAD Segment</em>'.
   * @generated
   */
  NADSegment createNADSegment();

  /**
   * Returns a new object of class '<em>DTM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DTM Segment</em>'.
   * @generated
   */
  DTMSegment createDTMSegment();

  /**
   * Returns a new object of class '<em>BGM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BGM Segment</em>'.
   * @generated
   */
  BGMSegment createBGMSegment();

  /**
   * Returns a new object of class '<em>PAT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAT Segment</em>'.
   * @generated
   */
  PATSegment createPATSegment();

  /**
   * Returns a new object of class '<em>FTX Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FTX Segment</em>'.
   * @generated
   */
  FTXSegment createFTXSegment();

  /**
   * Returns a new object of class '<em>ERC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ERC Segment</em>'.
   * @generated
   */
  ERCSegment createERCSegment();

  /**
   * Returns a new object of class '<em>CNT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CNT Segment</em>'.
   * @generated
   */
  CNTSegment createCNTSegment();

  /**
   * Returns a new object of class '<em>CTA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CTA Segment</em>'.
   * @generated
   */
  CTASegment createCTASegment();

  /**
   * Returns a new object of class '<em>PCI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PCI Segment</em>'.
   * @generated
   */
  PCISegment createPCISegment();

  /**
   * Returns a new object of class '<em>AAI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AAI Segment</em>'.
   * @generated
   */
  AAISegment createAAISegment();

  /**
   * Returns a new object of class '<em>ALS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ALS Segment</em>'.
   * @generated
   */
  ALSSegment createALSSegment();

  /**
   * Returns a new object of class '<em>ODS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ODS Segment</em>'.
   * @generated
   */
  ODSSegment createODSSegment();

  /**
   * Returns a new object of class '<em>APD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>APD Segment</em>'.
   * @generated
   */
  APDSegment createAPDSegment();

  /**
   * Returns a new object of class '<em>ADS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ADS Segment</em>'.
   * @generated
   */
  ADSSegment createADSSegment();

  /**
   * Returns a new object of class '<em>ERI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ERI Segment</em>'.
   * @generated
   */
  ERISegment createERISegment();

  /**
   * Returns a new object of class '<em>ATR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ATR Segment</em>'.
   * @generated
   */
  ATRSegment createATRSegment();

  /**
   * Returns a new object of class '<em>BCD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BCD Segment</em>'.
   * @generated
   */
  BCDSegment createBCDSegment();

  /**
   * Returns a new object of class '<em>BLI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BLI Segment</em>'.
   * @generated
   */
  BLISegment createBLISegment();

  /**
   * Returns a new object of class '<em>MOV Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MOV Segment</em>'.
   * @generated
   */
  MOVSegment createMOVSegment();

  /**
   * Returns a new object of class '<em>CLT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CLT Segment</em>'.
   * @generated
   */
  CLTSegment createCLTSegment();

  /**
   * Returns a new object of class '<em>CMN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CMN Segment</em>'.
   * @generated
   */
  CMNSegment createCMNSegment();

  /**
   * Returns a new object of class '<em>CNX Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CNX Segment</em>'.
   * @generated
   */
  CNXSegment createCNXSegment();

  /**
   * Returns a new object of class '<em>CRI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CRI Segment</em>'.
   * @generated
   */
  CRISegment createCRISegment();

  /**
   * Returns a new object of class '<em>CON Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CON Segment</em>'.
   * @generated
   */
  CONSegment createCONSegment();

  /**
   * Returns a new object of class '<em>CNY Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CNY Segment</em>'.
   * @generated
   */
  CNYSegment createCNYSegment();

  /**
   * Returns a new object of class '<em>CUR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CUR Segment</em>'.
   * @generated
   */
  CURSegment createCURSegment();

  /**
   * Returns a new object of class '<em>DAV Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DAV Segment</em>'.
   * @generated
   */
  DAVSegment createDAVSegment();

  /**
   * Returns a new object of class '<em>DTI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DTI Segment</em>'.
   * @generated
   */
  DTISegment createDTISegment();

  /**
   * Returns a new object of class '<em>DNT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DNT Segment</em>'.
   * @generated
   */
  DNTSegment createDNTSegment();

  /**
   * Returns a new object of class '<em>DIS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DIS Segment</em>'.
   * @generated
   */
  DISSegment createDISSegment();

  /**
   * Returns a new object of class '<em>SER Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SER Segment</em>'.
   * @generated
   */
  SERSegment createSERSegment();

  /**
   * Returns a new object of class '<em>FRM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FRM Segment</em>'.
   * @generated
   */
  FRMSegment createFRMSegment();

  /**
   * Returns a new object of class '<em>FRQ Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FRQ Segment</em>'.
   * @generated
   */
  FRQSegment createFRQSegment();

  /**
   * Returns a new object of class '<em>FTI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FTI Segment</em>'.
   * @generated
   */
  FTISegment createFTISegment();

  /**
   * Returns a new object of class '<em>HDI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>HDI Segment</em>'.
   * @generated
   */
  HDISegment createHDISegment();

  /**
   * Returns a new object of class '<em>HDR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>HDR Segment</em>'.
   * @generated
   */
  HDRSegment createHDRSegment();

  /**
   * Returns a new object of class '<em>ADI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ADI Segment</em>'.
   * @generated
   */
  ADISegment createADISegment();

  /**
   * Returns a new object of class '<em>HDS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>HDS Segment</em>'.
   * @generated
   */
  HDSSegment createHDSSegment();

  /**
   * Returns a new object of class '<em>ITD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ITD Segment</em>'.
   * @generated
   */
  ITDSegment createITDSegment();

  /**
   * Returns a new object of class '<em>ITC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ITC Segment</em>'.
   * @generated
   */
  ITCSegment createITCSegment();

  /**
   * Returns a new object of class '<em>ICI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ICI Segment</em>'.
   * @generated
   */
  ICISegment createICISegment();

  /**
   * Returns a new object of class '<em>IFT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IFT Segment</em>'.
   * @generated
   */
  IFTSegment createIFTSegment();

  /**
   * Returns a new object of class '<em>ITM Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ITM Segment</em>'.
   * @generated
   */
  ITMSegment createITMSegment();

  /**
   * Returns a new object of class '<em>LNG Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LNG Segment</em>'.
   * @generated
   */
  LNGSegment createLNGSegment();

  /**
   * Returns a new object of class '<em>LKP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LKP Segment</em>'.
   * @generated
   */
  LKPSegment createLKPSegment();

  /**
   * Returns a new object of class '<em>POR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>POR Segment</em>'.
   * @generated
   */
  PORSegment createPORSegment();

  /**
   * Returns a new object of class '<em>MES Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MES Segment</em>'.
   * @generated
   */
  MESSegment createMESSegment();

  /**
   * Returns a new object of class '<em>MSD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MSD Segment</em>'.
   * @generated
   */
  MSDSegment createMSDSegment();

  /**
   * Returns a new object of class '<em>MAP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MAP Segment</em>'.
   * @generated
   */
  MAPSegment createMAPSegment();

  /**
   * Returns a new object of class '<em>NME Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NME Segment</em>'.
   * @generated
   */
  NMESegment createNMESegment();

  /**
   * Returns a new object of class '<em>NAA Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NAA Segment</em>'.
   * @generated
   */
  NAASegment createNAASegment();

  /**
   * Returns a new object of class '<em>NUN Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NUN Segment</em>'.
   * @generated
   */
  NUNSegment createNUNSegment();

  /**
   * Returns a new object of class '<em>ODI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ODI Segment</em>'.
   * @generated
   */
  ODISegment createODISegment();

  /**
   * Returns a new object of class '<em>ORG Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ORG Segment</em>'.
   * @generated
   */
  ORGSegment createORGSegment();

  /**
   * Returns a new object of class '<em>OTI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>OTI Segment</em>'.
   * @generated
   */
  OTISegment createOTISegment();

  /**
   * Returns a new object of class '<em>PRT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PRT Segment</em>'.
   * @generated
   */
  PRTSegment createPRTSegment();

  /**
   * Returns a new object of class '<em>PMT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PMT Segment</em>'.
   * @generated
   */
  PMTSegment createPMTSegment();

  /**
   * Returns a new object of class '<em>POP Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>POP Segment</em>'.
   * @generated
   */
  POPSegment createPOPSegment();

  /**
   * Returns a new object of class '<em>POS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>POS Segment</em>'.
   * @generated
   */
  POSSegment createPOSSegment();

  /**
   * Returns a new object of class '<em>PRE Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PRE Segment</em>'.
   * @generated
   */
  PRESegment createPRESegment();

  /**
   * Returns a new object of class '<em>PRD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PRD Segment</em>'.
   * @generated
   */
  PRDSegment createPRDSegment();

  /**
   * Returns a new object of class '<em>PDT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PDT Segment</em>'.
   * @generated
   */
  PDTSegment createPDTSegment();

  /**
   * Returns a new object of class '<em>PLI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PLI Segment</em>'.
   * @generated
   */
  PLISegment createPLISegment();

  /**
   * Returns a new object of class '<em>PRO Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PRO Segment</em>'.
   * @generated
   */
  PROSegment createPROSegment();

  /**
   * Returns a new object of class '<em>QTI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QTI Segment</em>'.
   * @generated
   */
  QTISegment createQTISegment();

  /**
   * Returns a new object of class '<em>RTI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RTI Segment</em>'.
   * @generated
   */
  RTISegment createRTISegment();

  /**
   * Returns a new object of class '<em>RTC Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RTC Segment</em>'.
   * @generated
   */
  RTCSegment createRTCSegment();

  /**
   * Returns a new object of class '<em>RFR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RFR Segment</em>'.
   * @generated
   */
  RFRSegment createRFRSegment();

  /**
   * Returns a new object of class '<em>RLS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RLS Segment</em>'.
   * @generated
   */
  RLSSegment createRLSSegment();

  /**
   * Returns a new object of class '<em>RCI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RCI Segment</em>'.
   * @generated
   */
  RCISegment createRCISegment();

  /**
   * Returns a new object of class '<em>RUL Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RUL Segment</em>'.
   * @generated
   */
  RULSegment createRULSegment();

  /**
   * Returns a new object of class '<em>SDT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SDT Segment</em>'.
   * @generated
   */
  SDTSegment createSDTSegment();

  /**
   * Returns a new object of class '<em>ASD Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ASD Segment</em>'.
   * @generated
   */
  ASDSegment createASDSegment();

  /**
   * Returns a new object of class '<em>PSI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PSI Segment</em>'.
   * @generated
   */
  PSISegment createPSISegment();

  /**
   * Returns a new object of class '<em>SSR Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SSR Segment</em>'.
   * @generated
   */
  SSRSegment createSSRSegment();

  /**
   * Returns a new object of class '<em>TFF Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TFF Segment</em>'.
   * @generated
   */
  TFFSegment createTFFSegment();

  /**
   * Returns a new object of class '<em>TXS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TXS Segment</em>'.
   * @generated
   */
  TXSSegment createTXSSegment();

  /**
   * Returns a new object of class '<em>TCE Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TCE Segment</em>'.
   * @generated
   */
  TCESegment createTCESegment();

  /**
   * Returns a new object of class '<em>TIZ Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TIZ Segment</em>'.
   * @generated
   */
  TIZSegment createTIZSegment();

  /**
   * Returns a new object of class '<em>ATI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ATI Segment</em>'.
   * @generated
   */
  ATISegment createATISegment();

  /**
   * Returns a new object of class '<em>TRF Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TRF Segment</em>'.
   * @generated
   */
  TRFSegment createTRFSegment();

  /**
   * Returns a new object of class '<em>TVL Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TVL Segment</em>'.
   * @generated
   */
  TVLSegment createTVLSegment();

  /**
   * Returns a new object of class '<em>TDI Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TDI Segment</em>'.
   * @generated
   */
  TDISegment createTDISegment();

  /**
   * Returns a new object of class '<em>TIF Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TIF Segment</em>'.
   * @generated
   */
  TIFSegment createTIFSegment();

  /**
   * Returns a new object of class '<em>VEH Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VEH Segment</em>'.
   * @generated
   */
  VEHSegment createVEHSegment();

  /**
   * Returns a new object of class '<em>UNS Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNS Segment</em>'.
   * @generated
   */
  UNSSegment createUNSSegment();

  /**
   * Returns a new object of class '<em>UNT Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNT Segment</em>'.
   * @generated
   */
  UNTSegment createUNTSegment();

  /**
   * Returns a new object of class '<em>UNZ Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNZ Segment</em>'.
   * @generated
   */
  UNZSegment createUNZSegment();

  /**
   * Returns a new object of class '<em>UNE Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNE Segment</em>'.
   * @generated
   */
  UNESegment createUNESegment();

  /**
   * Returns a new object of class '<em>Abstract Edi Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Edi Function</em>'.
   * @generated
   */
  AbstractEdiFunction createAbstractEdiFunction();

  /**
   * Returns a new object of class '<em>UNB Header</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNB Header</em>'.
   * @generated
   */
  UNBHeader createUNBHeader();

  /**
   * Returns a new object of class '<em>Price Information</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Price Information</em>'.
   * @generated
   */
  PriceInformation createPriceInformation();

  /**
   * Returns a new object of class '<em>Message Body Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Body Function</em>'.
   * @generated
   */
  MessageBodyFunction createMessageBodyFunction();

  /**
   * Returns a new object of class '<em>Message Indentifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Indentifier</em>'.
   * @generated
   */
  MessageIndentifier createMessageIndentifier();

  /**
   * Returns a new object of class '<em>Relationship</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Relationship</em>'.
   * @generated
   */
  Relationship createRelationship();

  /**
   * Returns a new object of class '<em>Product Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Product Function</em>'.
   * @generated
   */
  ProductFunction createProductFunction();

  /**
   * Returns a new object of class '<em>Item Number Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Item Number Identification</em>'.
   * @generated
   */
  ItemNumberIdentification createItemNumberIdentification();

  /**
   * Returns a new object of class '<em>Subline Information</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Subline Information</em>'.
   * @generated
   */
  SublineInformation createSublineInformation();

  /**
   * Returns a new object of class '<em>Quantity Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quantity Detail</em>'.
   * @generated
   */
  QuantityDetail createQuantityDetail();

  /**
   * Returns a new object of class '<em>Street</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Street</em>'.
   * @generated
   */
  Street createStreet();

  /**
   * Returns a new object of class '<em>Country Sub Entity Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Country Sub Entity Detail</em>'.
   * @generated
   */
  CountrySubEntityDetail createCountrySubEntityDetail();

  /**
   * Returns a new object of class '<em>Party Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Party Name</em>'.
   * @generated
   */
  PartyName createPartyName();

  /**
   * Returns a new object of class '<em>Name And Address</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Name And Address</em>'.
   * @generated
   */
  NameAndAddress createNameAndAddress();

  /**
   * Returns a new object of class '<em>Party Identification Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Party Identification Detail</em>'.
   * @generated
   */
  PartyIdentificationDetail createPartyIdentificationDetail();

  /**
   * Returns a new object of class '<em>Application Error Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Application Error Detail</em>'.
   * @generated
   */
  ApplicationErrorDetail createApplicationErrorDetail();

  /**
   * Returns a new object of class '<em>System Detail Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System Detail Function</em>'.
   * @generated
   */
  SystemDetailFunction createSystemDetailFunction();

  /**
   * Returns a new object of class '<em>Tax Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tax Detail</em>'.
   * @generated
   */
  TaxDetail createTaxDetail();

  /**
   * Returns a new object of class '<em>Tax Account Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tax Account Detail</em>'.
   * @generated
   */
  TaxAccountDetail createTaxAccountDetail();

  /**
   * Returns a new object of class '<em>Tax Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tax Type</em>'.
   * @generated
   */
  TaxType createTaxType();

  /**
   * Returns a new object of class '<em>Currency Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Currency Detail</em>'.
   * @generated
   */
  CurrencyDetail createCurrencyDetail();

  /**
   * Returns a new object of class '<em>Document Message Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Document Message Identification</em>'.
   * @generated
   */
  DocumentMessageIdentification createDocumentMessageIdentification();

  /**
   * Returns a new object of class '<em>Document Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Document Message</em>'.
   * @generated
   */
  DocumentMessage createDocumentMessage();

  /**
   * Returns a new object of class '<em>Originator Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Originator Function</em>'.
   * @generated
   */
  OriginatorFunction createOriginatorFunction();

  /**
   * Returns a new object of class '<em>Originator Identification Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Originator Identification Function</em>'.
   * @generated
   */
  OriginatorIdentificationFunction createOriginatorIdentificationFunction();

  /**
   * Returns a new object of class '<em>Location</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Location</em>'.
   * @generated
   */
  Location createLocation();

  /**
   * Returns a new object of class '<em>Interchanger Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interchanger Function</em>'.
   * @generated
   */
  InterchangerFunction createInterchangerFunction();

  /**
   * Returns a new object of class '<em>Location Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Location Identification</em>'.
   * @generated
   */
  LocationIdentification createLocationIdentification();

  /**
   * Returns a new object of class '<em>Address Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Address Detail</em>'.
   * @generated
   */
  AddressDetail createAddressDetail();

  /**
   * Returns a new object of class '<em>Address Usage</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Address Usage</em>'.
   * @generated
   */
  AddressUsage createAddressUsage();

  /**
   * Returns a new object of class '<em>Attribute Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Detail</em>'.
   * @generated
   */
  AttributeDetail createAttributeDetail();

  /**
   * Returns a new object of class '<em>Attribute Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Type</em>'.
   * @generated
   */
  AttributeType createAttributeType();

  /**
   * Returns a new object of class '<em>Bank Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bank Operation</em>'.
   * @generated
   */
  BankOperation createBankOperation();

  /**
   * Returns a new object of class '<em>Business Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Business Function</em>'.
   * @generated
   */
  BusinessFunction createBusinessFunction();

  /**
   * Returns a new object of class '<em>Department Employee Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Department Employee Detail</em>'.
   * @generated
   */
  DepartmentEmployeeDetail createDepartmentEmployeeDetail();

  /**
   * Returns a new object of class '<em>Identification Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Identification Number</em>'.
   * @generated
   */
  IdentificationNumber createIdentificationNumber();

  /**
   * Returns a new object of class '<em>Position Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Position Identification</em>'.
   * @generated
   */
  PositionIdentification createPositionIdentification();

  /**
   * Returns a new object of class '<em>Product Characteristic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Product Characteristic</em>'.
   * @generated
   */
  ProductCharacteristic createProductCharacteristic();

  /**
   * Returns a new object of class '<em>Nationality Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nationality Detail</em>'.
   * @generated
   */
  NationalityDetail createNationalityDetail();

  /**
   * Returns a new object of class '<em>Percentage Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Percentage Detail</em>'.
   * @generated
   */
  PercentageDetail createPercentageDetail();

  /**
   * Returns a new object of class '<em>Rate Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rate Detail</em>'.
   * @generated
   */
  RateDetail createRateDetail();

  /**
   * Returns a new object of class '<em>Status Category</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Status Category</em>'.
   * @generated
   */
  StatusCategory createStatusCategory();

  /**
   * Returns a new object of class '<em>Status</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Status</em>'.
   * @generated
   */
  Status createStatus();

  /**
   * Returns a new object of class '<em>Status Reason</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Status Reason</em>'.
   * @generated
   */
  StatusReason createStatusReason();

  /**
   * Returns a new object of class '<em>Value List Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value List Identification</em>'.
   * @generated
   */
  ValueListIdentification createValueListIdentification();

  /**
   * Returns a new object of class '<em>Terms Of Delivery Transport</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terms Of Delivery Transport</em>'.
   * @generated
   */
  TermsOfDeliveryTransport createTermsOfDeliveryTransport();

  /**
   * Returns a new object of class '<em>Quantity Difference Information</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quantity Difference Information</em>'.
   * @generated
   */
  QuantityDifferenceInformation createQuantityDifferenceInformation();

  /**
   * Returns a new object of class '<em>Reason For Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reason For Change</em>'.
   * @generated
   */
  ReasonForChange createReasonForChange();

  /**
   * Returns a new object of class '<em>Language Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Language Detail</em>'.
   * @generated
   */
  LanguageDetail createLanguageDetail();

  /**
   * Returns a new object of class '<em>Information Request</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Information Request</em>'.
   * @generated
   */
  InformationRequest createInformationRequest();

  /**
   * Returns a new object of class '<em>Index Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Index Identification</em>'.
   * @generated
   */
  IndexIdentification createIndexIdentification();

  /**
   * Returns a new object of class '<em>Index Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Index Value</em>'.
   * @generated
   */
  IndexValue createIndexValue();

  /**
   * Returns a new object of class '<em>Control</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Control</em>'.
   * @generated
   */
  Control createControl();

  /**
   * Returns a new object of class '<em>Basis Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Basis Type</em>'.
   * @generated
   */
  BasisType createBasisType();

  /**
   * Returns a new object of class '<em>Communication Contact</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Communication Contact</em>'.
   * @generated
   */
  CommunicationContact createCommunicationContact();

  /**
   * Returns a new object of class '<em>Agreement Type Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Agreement Type Identification</em>'.
   * @generated
   */
  AgreementTypeIdentification createAgreementTypeIdentification();

  /**
   * Returns a new object of class '<em>Allowance Charge Information</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Allowance Charge Information</em>'.
   * @generated
   */
  AllowanceChargeInformation createAllowanceChargeInformation();

  /**
   * Returns a new object of class '<em>Special Services Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Special Services Identification</em>'.
   * @generated
   */
  SpecialServicesIdentification createSpecialServicesIdentification();

  /**
   * Returns a new object of class '<em>Applicability Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Applicability Type</em>'.
   * @generated
   */
  ApplicabilityType createApplicabilityType();

  /**
   * Returns a new object of class '<em>Price Multiplier Information</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Price Multiplier Information</em>'.
   * @generated
   */
  PriceMultiplierInformation createPriceMultiplierInformation();

  /**
   * Returns a new object of class '<em>Monetary Amount Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Monetary Amount Function</em>'.
   * @generated
   */
  MonetaryAmountFunction createMonetaryAmountFunction();

  /**
   * Returns a new object of class '<em>Monetary Amount Function Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Monetary Amount Function Detail</em>'.
   * @generated
   */
  MonetaryAmountFunctionDetail createMonetaryAmountFunctionDetail();

  /**
   * Returns a new object of class '<em>Array Cell Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Array Cell Detail</em>'.
   * @generated
   */
  ArrayCellDetail createArrayCellDetail();

  /**
   * Returns a new object of class '<em>Array Structure Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Array Structure Identification</em>'.
   * @generated
   */
  ArrayStructureIdentification createArrayStructureIdentification();

  /**
   * Returns a new object of class '<em>Bill Level Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bill Level Identification</em>'.
   * @generated
   */
  BillLevelIdentification createBillLevelIdentification();

  /**
   * Returns a new object of class '<em>Characteristic Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Characteristic Value</em>'.
   * @generated
   */
  CharacteristicValue createCharacteristicValue();

  /**
   * Returns a new object of class '<em>Measurement Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Measurement Detail</em>'.
   * @generated
   */
  MeasurementDetail createMeasurementDetail();

  /**
   * Returns a new object of class '<em>Physical Logical State Information</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Physical Logical State Information</em>'.
   * @generated
   */
  PhysicalLogicalStateInformation createPhysicalLogicalStateInformation();

  /**
   * Returns a new object of class '<em>Code Set Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Code Set Identification</em>'.
   * @generated
   */
  CodeSetIdentification createCodeSetIdentification();

  /**
   * Returns a new object of class '<em>Computer Environment Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Computer Environment Identification</em>'.
   * @generated
   */
  ComputerEnvironmentIdentification createComputerEnvironmentIdentification();

  /**
   * Returns a new object of class '<em>Clinical Information Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Clinical Information Detail</em>'.
   * @generated
   */
  ClinicalInformationDetail createClinicalInformationDetail();

  /**
   * Returns a new object of class '<em>Certainty Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Certainty Detail</em>'.
   * @generated
   */
  CertaintyDetail createCertaintyDetail();

  /**
   * Returns a new object of class '<em>Clause Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Clause Name</em>'.
   * @generated
   */
  ClauseName createClauseName();

  /**
   * Returns a new object of class '<em>Clinical Intervention Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Clinical Intervention Detail</em>'.
   * @generated
   */
  ClinicalInterventionDetail createClinicalInterventionDetail();

  /**
   * Returns a new object of class '<em>Processing Indicator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Processing Indicator</em>'.
   * @generated
   */
  ProcessingIndicator createProcessingIndicator();

  /**
   * Returns a new object of class '<em>Marks Labels</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Marks Labels</em>'.
   * @generated
   */
  MarksLabels createMarksLabels();

  /**
   * Returns a new object of class '<em>Type Of Marking</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Of Marking</em>'.
   * @generated
   */
  TypeOfMarking createTypeOfMarking();

  /**
   * Returns a new object of class '<em>Government Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Government Action</em>'.
   * @generated
   */
  GovernmentAction createGovernmentAction();

  /**
   * Returns a new object of class '<em>Product Date Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Product Date Time</em>'.
   * @generated
   */
  ProductDateTime createProductDateTime();

  /**
   * Returns a new object of class '<em>Company Identification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Company Identification</em>'.
   * @generated
   */
  CompanyIdentification createCompanyIdentification();

  /**
   * Returns a new object of class '<em>Product Identification Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Product Identification Detail</em>'.
   * @generated
   */
  ProductIdentificationDetail createProductIdentificationDetail();

  /**
   * Returns a new object of class '<em>Sequence Number Detail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sequence Number Detail</em>'.
   * @generated
   */
  SequenceNumberDetail createSequenceNumberDetail();

  /**
   * Returns a new object of class '<em>Date And Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Date And Time</em>'.
   * @generated
   */
  DateAndTime createDateAndTime();

  /**
   * Returns a new object of class '<em>Date Only</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Date Only</em>'.
   * @generated
   */
  DateOnly createDateOnly();

  /**
   * Returns a new object of class '<em>Date With Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Date With Time</em>'.
   * @generated
   */
  DateWithTime createDateWithTime();

  /**
   * Returns a new object of class '<em>Date Time Period</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Date Time Period</em>'.
   * @generated
   */
  DateTimePeriod createDateTimePeriod();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  EdilangPackage getEdilangPackage();

} //EdilangFactory
