/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ERC Segment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.ERCSegment#getApplicationErrorDetails <em>Application Error Details</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getERCSegment()
 * @model
 * @generated
 */
public interface ERCSegment extends AbstractEdiSegment
{
  /**
   * Returns the value of the '<em><b>Application Error Details</b></em>' containment reference list.
   * The list contents are of type {@link io.thlaegler.edifact.edilang.ApplicationErrorDetail}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Application Error Details</em>' containment reference list.
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getERCSegment_ApplicationErrorDetails()
   * @model containment="true"
   * @generated
   */
  EList<ApplicationErrorDetail> getApplicationErrorDetails();

} // ERCSegment
