/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GIS Segment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.GISSegment#getProcessingIndicator <em>Processing Indicator</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getGISSegment()
 * @model
 * @generated
 */
public interface GISSegment extends AbstractEdiSegment
{
  /**
   * Returns the value of the '<em><b>Processing Indicator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processing Indicator</em>' containment reference.
   * @see #setProcessingIndicator(ProcessingIndicator)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getGISSegment_ProcessingIndicator()
   * @model containment="true"
   * @generated
   */
  ProcessingIndicator getProcessingIndicator();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.GISSegment#getProcessingIndicator <em>Processing Indicator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Processing Indicator</em>' containment reference.
   * @see #getProcessingIndicator()
   * @generated
   */
  void setProcessingIndicator(ProcessingIndicator value);

} // GISSegment
