/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Monetary Amount Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.MonetaryAmountFunction#getMonetaryAmountFunctionDescriptionCode <em>Monetary Amount Function Description Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.MonetaryAmountFunction#getCodeListIdentificationCode <em>Code List Identification Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.MonetaryAmountFunction#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.MonetaryAmountFunction#getMonetaryAmountFunctionDescription <em>Monetary Amount Function Description</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getMonetaryAmountFunction()
 * @model
 * @generated
 */
public interface MonetaryAmountFunction extends EObject
{
  /**
   * Returns the value of the '<em><b>Monetary Amount Function Description Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Monetary Amount Function Description Code</em>' attribute.
   * @see #setMonetaryAmountFunctionDescriptionCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getMonetaryAmountFunction_MonetaryAmountFunctionDescriptionCode()
   * @model
   * @generated
   */
  String getMonetaryAmountFunctionDescriptionCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.MonetaryAmountFunction#getMonetaryAmountFunctionDescriptionCode <em>Monetary Amount Function Description Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Monetary Amount Function Description Code</em>' attribute.
   * @see #getMonetaryAmountFunctionDescriptionCode()
   * @generated
   */
  void setMonetaryAmountFunctionDescriptionCode(String value);

  /**
   * Returns the value of the '<em><b>Code List Identification Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code List Identification Code</em>' attribute.
   * @see #setCodeListIdentificationCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getMonetaryAmountFunction_CodeListIdentificationCode()
   * @model
   * @generated
   */
  String getCodeListIdentificationCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.MonetaryAmountFunction#getCodeListIdentificationCode <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code List Identification Code</em>' attribute.
   * @see #getCodeListIdentificationCode()
   * @generated
   */
  void setCodeListIdentificationCode(String value);

  /**
   * Returns the value of the '<em><b>Code List Responsible Agency Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code List Responsible Agency Code</em>' attribute.
   * @see #setCodeListResponsibleAgencyCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getMonetaryAmountFunction_CodeListResponsibleAgencyCode()
   * @model
   * @generated
   */
  String getCodeListResponsibleAgencyCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.MonetaryAmountFunction#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code List Responsible Agency Code</em>' attribute.
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   */
  void setCodeListResponsibleAgencyCode(String value);

  /**
   * Returns the value of the '<em><b>Monetary Amount Function Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Monetary Amount Function Description</em>' attribute.
   * @see #setMonetaryAmountFunctionDescription(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getMonetaryAmountFunction_MonetaryAmountFunctionDescription()
   * @model
   * @generated
   */
  String getMonetaryAmountFunctionDescription();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.MonetaryAmountFunction#getMonetaryAmountFunctionDescription <em>Monetary Amount Function Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Monetary Amount Function Description</em>' attribute.
   * @see #getMonetaryAmountFunctionDescription()
   * @generated
   */
  void setMonetaryAmountFunctionDescription(String value);

} // MonetaryAmountFunction
