/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>NAD Segment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.NADSegment#getCode <em>Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.NADSegment#getManufacturer1 <em>Manufacturer1</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.NADSegment#getManufacturer2 <em>Manufacturer2</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.NADSegment#getManufacturer3 <em>Manufacturer3</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getNADSegment()
 * @model
 * @generated
 */
public interface NADSegment extends AbstractEdiSegment
{
  /**
   * Returns the value of the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code</em>' attribute.
   * @see #setCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getNADSegment_Code()
   * @model
   * @generated
   */
  String getCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.NADSegment#getCode <em>Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code</em>' attribute.
   * @see #getCode()
   * @generated
   */
  void setCode(String value);

  /**
   * Returns the value of the '<em><b>Manufacturer1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manufacturer1</em>' attribute.
   * @see #setManufacturer1(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getNADSegment_Manufacturer1()
   * @model
   * @generated
   */
  String getManufacturer1();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.NADSegment#getManufacturer1 <em>Manufacturer1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manufacturer1</em>' attribute.
   * @see #getManufacturer1()
   * @generated
   */
  void setManufacturer1(String value);

  /**
   * Returns the value of the '<em><b>Manufacturer2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manufacturer2</em>' attribute.
   * @see #setManufacturer2(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getNADSegment_Manufacturer2()
   * @model
   * @generated
   */
  String getManufacturer2();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.NADSegment#getManufacturer2 <em>Manufacturer2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manufacturer2</em>' attribute.
   * @see #getManufacturer2()
   * @generated
   */
  void setManufacturer2(String value);

  /**
   * Returns the value of the '<em><b>Manufacturer3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manufacturer3</em>' attribute.
   * @see #setManufacturer3(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getNADSegment_Manufacturer3()
   * @model
   * @generated
   */
  String getManufacturer3();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.NADSegment#getManufacturer3 <em>Manufacturer3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manufacturer3</em>' attribute.
   * @see #getManufacturer3()
   * @generated
   */
  void setManufacturer3(String value);

} // NADSegment
