/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Party Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.PartyName#getPartyName <em>Party Name</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getPartyName()
 * @model
 * @generated
 */
public interface PartyName extends AbstractEdiFunction
{
  /**
   * Returns the value of the '<em><b>Party Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Party Name</em>' attribute list.
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getPartyName_PartyName()
   * @model unique="false"
   * @generated
   */
  EList<String> getPartyName();

} // PartyName
