/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Price Multiplier Information</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.PriceMultiplierInformation#getPriceMultiplierRate <em>Price Multiplier Rate</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.PriceMultiplierInformation#getPriceMultiplierTypeCodeQualifier <em>Price Multiplier Type Code Qualifier</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getPriceMultiplierInformation()
 * @model
 * @generated
 */
public interface PriceMultiplierInformation extends EObject
{
  /**
   * Returns the value of the '<em><b>Price Multiplier Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Price Multiplier Rate</em>' attribute.
   * @see #setPriceMultiplierRate(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getPriceMultiplierInformation_PriceMultiplierRate()
   * @model
   * @generated
   */
  String getPriceMultiplierRate();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.PriceMultiplierInformation#getPriceMultiplierRate <em>Price Multiplier Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Price Multiplier Rate</em>' attribute.
   * @see #getPriceMultiplierRate()
   * @generated
   */
  void setPriceMultiplierRate(String value);

  /**
   * Returns the value of the '<em><b>Price Multiplier Type Code Qualifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Price Multiplier Type Code Qualifier</em>' attribute.
   * @see #setPriceMultiplierTypeCodeQualifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getPriceMultiplierInformation_PriceMultiplierTypeCodeQualifier()
   * @model
   * @generated
   */
  String getPriceMultiplierTypeCodeQualifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.PriceMultiplierInformation#getPriceMultiplierTypeCodeQualifier <em>Price Multiplier Type Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Price Multiplier Type Code Qualifier</em>' attribute.
   * @see #getPriceMultiplierTypeCodeQualifier()
   * @generated
   */
  void setPriceMultiplierTypeCodeQualifier(String value);

} // PriceMultiplierInformation
