/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quantity Detail</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.QuantityDetail#getQuantityTypeCodeQualifier <em>Quantity Type Code Qualifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.QuantityDetail#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.QuantityDetail#getMeasurementUnitCode <em>Measurement Unit Code</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getQuantityDetail()
 * @model
 * @generated
 */
public interface QuantityDetail extends AbstractEdiFunction
{
  /**
   * Returns the value of the '<em><b>Quantity Type Code Qualifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity Type Code Qualifier</em>' attribute.
   * @see #setQuantityTypeCodeQualifier(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getQuantityDetail_QuantityTypeCodeQualifier()
   * @model
   * @generated
   */
  String getQuantityTypeCodeQualifier();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.QuantityDetail#getQuantityTypeCodeQualifier <em>Quantity Type Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity Type Code Qualifier</em>' attribute.
   * @see #getQuantityTypeCodeQualifier()
   * @generated
   */
  void setQuantityTypeCodeQualifier(String value);

  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getQuantityDetail_Quantity()
   * @model
   * @generated
   */
  String getQuantity();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.QuantityDetail#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(String value);

  /**
   * Returns the value of the '<em><b>Measurement Unit Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Measurement Unit Code</em>' attribute.
   * @see #setMeasurementUnitCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getQuantityDetail_MeasurementUnitCode()
   * @model
   * @generated
   */
  String getMeasurementUnitCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.QuantityDetail#getMeasurementUnitCode <em>Measurement Unit Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Measurement Unit Code</em>' attribute.
   * @see #getMeasurementUnitCode()
   * @generated
   */
  void setMeasurementUnitCode(String value);

} // QuantityDetail
