/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RFF Segment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.RFFSegment#getRff1 <em>Rff1</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.RFFSegment#getRff2 <em>Rff2</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getRFFSegment()
 * @model
 * @generated
 */
public interface RFFSegment extends AbstractEdiSegment
{
  /**
   * Returns the value of the '<em><b>Rff1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rff1</em>' attribute.
   * @see #setRff1(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getRFFSegment_Rff1()
   * @model
   * @generated
   */
  String getRff1();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.RFFSegment#getRff1 <em>Rff1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rff1</em>' attribute.
   * @see #getRff1()
   * @generated
   */
  void setRff1(String value);

  /**
   * Returns the value of the '<em><b>Rff2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rff2</em>' attribute.
   * @see #setRff2(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getRFFSegment_Rff2()
   * @model
   * @generated
   */
  String getRff2();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.RFFSegment#getRff2 <em>Rff2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rff2</em>' attribute.
   * @see #getRff2()
   * @generated
   */
  void setRff2(String value);

} // RFFSegment
