/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UCI Segment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.UCISegment#getInterchangeControlReference <em>Interchange Control Reference</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.UCISegment#getInterchangeSender <em>Interchange Sender</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.UCISegment#getInterchangeRecipient <em>Interchange Recipient</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.UCISegment#getAction <em>Action</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.UCISegment#getSyntaxErrorCode <em>Syntax Error Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.UCISegment#getSegmentTagCode <em>Segment Tag Code</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getUCISegment()
 * @model
 * @generated
 */
public interface UCISegment extends AbstractEdiSegment
{
  /**
   * Returns the value of the '<em><b>Interchange Control Reference</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interchange Control Reference</em>' attribute.
   * @see #setInterchangeControlReference(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getUCISegment_InterchangeControlReference()
   * @model
   * @generated
   */
  String getInterchangeControlReference();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.UCISegment#getInterchangeControlReference <em>Interchange Control Reference</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interchange Control Reference</em>' attribute.
   * @see #getInterchangeControlReference()
   * @generated
   */
  void setInterchangeControlReference(String value);

  /**
   * Returns the value of the '<em><b>Interchange Sender</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interchange Sender</em>' attribute.
   * @see #setInterchangeSender(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getUCISegment_InterchangeSender()
   * @model
   * @generated
   */
  String getInterchangeSender();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.UCISegment#getInterchangeSender <em>Interchange Sender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interchange Sender</em>' attribute.
   * @see #getInterchangeSender()
   * @generated
   */
  void setInterchangeSender(String value);

  /**
   * Returns the value of the '<em><b>Interchange Recipient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interchange Recipient</em>' attribute.
   * @see #setInterchangeRecipient(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getUCISegment_InterchangeRecipient()
   * @model
   * @generated
   */
  String getInterchangeRecipient();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.UCISegment#getInterchangeRecipient <em>Interchange Recipient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interchange Recipient</em>' attribute.
   * @see #getInterchangeRecipient()
   * @generated
   */
  void setInterchangeRecipient(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getUCISegment_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.UCISegment#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

  /**
   * Returns the value of the '<em><b>Syntax Error Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Syntax Error Code</em>' attribute.
   * @see #setSyntaxErrorCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getUCISegment_SyntaxErrorCode()
   * @model
   * @generated
   */
  String getSyntaxErrorCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.UCISegment#getSyntaxErrorCode <em>Syntax Error Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Syntax Error Code</em>' attribute.
   * @see #getSyntaxErrorCode()
   * @generated
   */
  void setSyntaxErrorCode(String value);

  /**
   * Returns the value of the '<em><b>Segment Tag Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Segment Tag Code</em>' attribute.
   * @see #setSegmentTagCode(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getUCISegment_SegmentTagCode()
   * @model
   * @generated
   */
  String getSegmentTagCode();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.UCISegment#getSegmentTagCode <em>Segment Tag Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Segment Tag Code</em>' attribute.
   * @see #getSegmentTagCode()
   * @generated
   */
  void setSegmentTagCode(String value);

} // UCISegment
