/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UNT Segment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.UNTSegment#getSegmentCount <em>Segment Count</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.UNTSegment#getMessageReferenceNumber <em>Message Reference Number</em>}</li>
 * </ul>
 *
 * @see io.thlaegler.edifact.edilang.EdilangPackage#getUNTSegment()
 * @model
 * @generated
 */
public interface UNTSegment extends AbstractEdiSegment
{
  /**
   * Returns the value of the '<em><b>Segment Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Segment Count</em>' attribute.
   * @see #setSegmentCount(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getUNTSegment_SegmentCount()
   * @model
   * @generated
   */
  String getSegmentCount();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.UNTSegment#getSegmentCount <em>Segment Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Segment Count</em>' attribute.
   * @see #getSegmentCount()
   * @generated
   */
  void setSegmentCount(String value);

  /**
   * Returns the value of the '<em><b>Message Reference Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message Reference Number</em>' attribute.
   * @see #setMessageReferenceNumber(String)
   * @see io.thlaegler.edifact.edilang.EdilangPackage#getUNTSegment_MessageReferenceNumber()
   * @model
   * @generated
   */
  String getMessageReferenceNumber();

  /**
   * Sets the value of the '{@link io.thlaegler.edifact.edilang.UNTSegment#getMessageReferenceNumber <em>Message Reference Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message Reference Number</em>' attribute.
   * @see #getMessageReferenceNumber()
   * @generated
   */
  void setMessageReferenceNumber(String value);

} // UNTSegment
