/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.AJTSegment;
import io.thlaegler.edifact.edilang.EdilangPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>AJT Segment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.AJTSegmentImpl#getAdjustmentReasonDescriptionCode <em>Adjustment Reason Description Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.AJTSegmentImpl#getLineItemIdentifier <em>Line Item Identifier</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AJTSegmentImpl extends AbstractEdiSegmentImpl implements AJTSegment
{
  /**
   * The default value of the '{@link #getAdjustmentReasonDescriptionCode() <em>Adjustment Reason Description Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdjustmentReasonDescriptionCode()
   * @generated
   * @ordered
   */
  protected static final String ADJUSTMENT_REASON_DESCRIPTION_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAdjustmentReasonDescriptionCode() <em>Adjustment Reason Description Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdjustmentReasonDescriptionCode()
   * @generated
   * @ordered
   */
  protected String adjustmentReasonDescriptionCode = ADJUSTMENT_REASON_DESCRIPTION_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getLineItemIdentifier() <em>Line Item Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineItemIdentifier()
   * @generated
   * @ordered
   */
  protected static final String LINE_ITEM_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLineItemIdentifier() <em>Line Item Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineItemIdentifier()
   * @generated
   * @ordered
   */
  protected String lineItemIdentifier = LINE_ITEM_IDENTIFIER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AJTSegmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getAJTSegment();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAdjustmentReasonDescriptionCode()
  {
    return adjustmentReasonDescriptionCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAdjustmentReasonDescriptionCode(String newAdjustmentReasonDescriptionCode)
  {
    String oldAdjustmentReasonDescriptionCode = adjustmentReasonDescriptionCode;
    adjustmentReasonDescriptionCode = newAdjustmentReasonDescriptionCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.AJT_SEGMENT__ADJUSTMENT_REASON_DESCRIPTION_CODE, oldAdjustmentReasonDescriptionCode, adjustmentReasonDescriptionCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLineItemIdentifier()
  {
    return lineItemIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLineItemIdentifier(String newLineItemIdentifier)
  {
    String oldLineItemIdentifier = lineItemIdentifier;
    lineItemIdentifier = newLineItemIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.AJT_SEGMENT__LINE_ITEM_IDENTIFIER, oldLineItemIdentifier, lineItemIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.AJT_SEGMENT__ADJUSTMENT_REASON_DESCRIPTION_CODE:
        return getAdjustmentReasonDescriptionCode();
      case EdilangPackage.AJT_SEGMENT__LINE_ITEM_IDENTIFIER:
        return getLineItemIdentifier();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.AJT_SEGMENT__ADJUSTMENT_REASON_DESCRIPTION_CODE:
        setAdjustmentReasonDescriptionCode((String)newValue);
        return;
      case EdilangPackage.AJT_SEGMENT__LINE_ITEM_IDENTIFIER:
        setLineItemIdentifier((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.AJT_SEGMENT__ADJUSTMENT_REASON_DESCRIPTION_CODE:
        setAdjustmentReasonDescriptionCode(ADJUSTMENT_REASON_DESCRIPTION_CODE_EDEFAULT);
        return;
      case EdilangPackage.AJT_SEGMENT__LINE_ITEM_IDENTIFIER:
        setLineItemIdentifier(LINE_ITEM_IDENTIFIER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.AJT_SEGMENT__ADJUSTMENT_REASON_DESCRIPTION_CODE:
        return ADJUSTMENT_REASON_DESCRIPTION_CODE_EDEFAULT == null ? adjustmentReasonDescriptionCode != null : !ADJUSTMENT_REASON_DESCRIPTION_CODE_EDEFAULT.equals(adjustmentReasonDescriptionCode);
      case EdilangPackage.AJT_SEGMENT__LINE_ITEM_IDENTIFIER:
        return LINE_ITEM_IDENTIFIER_EDEFAULT == null ? lineItemIdentifier != null : !LINE_ITEM_IDENTIFIER_EDEFAULT.equals(lineItemIdentifier);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (adjustmentReasonDescriptionCode: ");
    result.append(adjustmentReasonDescriptionCode);
    result.append(", lineItemIdentifier: ");
    result.append(lineItemIdentifier);
    result.append(')');
    return result.toString();
  }

} //AJTSegmentImpl
