/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.ARDSegment;
import io.thlaegler.edifact.edilang.EdilangPackage;
import io.thlaegler.edifact.edilang.MonetaryAmountFunction;
import io.thlaegler.edifact.edilang.MonetaryAmountFunctionDetail;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>ARD Segment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.ARDSegmentImpl#getMonetaryAmountFunction <em>Monetary Amount Function</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.ARDSegmentImpl#getMonetaryAmountFunctionDetails <em>Monetary Amount Function Details</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ARDSegmentImpl extends AbstractEdiSegmentImpl implements ARDSegment
{
  /**
   * The cached value of the '{@link #getMonetaryAmountFunction() <em>Monetary Amount Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMonetaryAmountFunction()
   * @generated
   * @ordered
   */
  protected MonetaryAmountFunction monetaryAmountFunction;

  /**
   * The cached value of the '{@link #getMonetaryAmountFunctionDetails() <em>Monetary Amount Function Details</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMonetaryAmountFunctionDetails()
   * @generated
   * @ordered
   */
  protected EList<MonetaryAmountFunctionDetail> monetaryAmountFunctionDetails;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ARDSegmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getARDSegment();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MonetaryAmountFunction getMonetaryAmountFunction()
  {
    return monetaryAmountFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMonetaryAmountFunction(MonetaryAmountFunction newMonetaryAmountFunction, NotificationChain msgs)
  {
    MonetaryAmountFunction oldMonetaryAmountFunction = monetaryAmountFunction;
    monetaryAmountFunction = newMonetaryAmountFunction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION, oldMonetaryAmountFunction, newMonetaryAmountFunction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMonetaryAmountFunction(MonetaryAmountFunction newMonetaryAmountFunction)
  {
    if (newMonetaryAmountFunction != monetaryAmountFunction)
    {
      NotificationChain msgs = null;
      if (monetaryAmountFunction != null)
        msgs = ((InternalEObject)monetaryAmountFunction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION, null, msgs);
      if (newMonetaryAmountFunction != null)
        msgs = ((InternalEObject)newMonetaryAmountFunction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION, null, msgs);
      msgs = basicSetMonetaryAmountFunction(newMonetaryAmountFunction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION, newMonetaryAmountFunction, newMonetaryAmountFunction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MonetaryAmountFunctionDetail> getMonetaryAmountFunctionDetails()
  {
    if (monetaryAmountFunctionDetails == null)
    {
      monetaryAmountFunctionDetails = new EObjectContainmentEList<MonetaryAmountFunctionDetail>(MonetaryAmountFunctionDetail.class, this, EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION_DETAILS);
    }
    return monetaryAmountFunctionDetails;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION:
        return basicSetMonetaryAmountFunction(null, msgs);
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION_DETAILS:
        return ((InternalEList<?>)getMonetaryAmountFunctionDetails()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION:
        return getMonetaryAmountFunction();
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION_DETAILS:
        return getMonetaryAmountFunctionDetails();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION:
        setMonetaryAmountFunction((MonetaryAmountFunction)newValue);
        return;
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION_DETAILS:
        getMonetaryAmountFunctionDetails().clear();
        getMonetaryAmountFunctionDetails().addAll((Collection<? extends MonetaryAmountFunctionDetail>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION:
        setMonetaryAmountFunction((MonetaryAmountFunction)null);
        return;
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION_DETAILS:
        getMonetaryAmountFunctionDetails().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION:
        return monetaryAmountFunction != null;
      case EdilangPackage.ARD_SEGMENT__MONETARY_AMOUNT_FUNCTION_DETAILS:
        return monetaryAmountFunctionDetails != null && !monetaryAmountFunctionDetails.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ARDSegmentImpl
