/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.BillLevelIdentification;
import io.thlaegler.edifact.edilang.EdilangPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bill Level Identification</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.BillLevelIdentificationImpl#getLevelOneIdentifier <em>Level One Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.BillLevelIdentificationImpl#getLevelTwoIdentifier <em>Level Two Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.BillLevelIdentificationImpl#getLevelThreeIdentifier <em>Level Three Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.BillLevelIdentificationImpl#getLevelFourIdentifier <em>Level Four Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.BillLevelIdentificationImpl#getLevelFiveIdentifier <em>Level Five Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.BillLevelIdentificationImpl#getLevelSixIdentifier <em>Level Six Identifier</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BillLevelIdentificationImpl extends MinimalEObjectImpl.Container implements BillLevelIdentification
{
  /**
   * The default value of the '{@link #getLevelOneIdentifier() <em>Level One Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelOneIdentifier()
   * @generated
   * @ordered
   */
  protected static final String LEVEL_ONE_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLevelOneIdentifier() <em>Level One Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelOneIdentifier()
   * @generated
   * @ordered
   */
  protected String levelOneIdentifier = LEVEL_ONE_IDENTIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getLevelTwoIdentifier() <em>Level Two Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelTwoIdentifier()
   * @generated
   * @ordered
   */
  protected static final String LEVEL_TWO_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLevelTwoIdentifier() <em>Level Two Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelTwoIdentifier()
   * @generated
   * @ordered
   */
  protected String levelTwoIdentifier = LEVEL_TWO_IDENTIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getLevelThreeIdentifier() <em>Level Three Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelThreeIdentifier()
   * @generated
   * @ordered
   */
  protected static final String LEVEL_THREE_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLevelThreeIdentifier() <em>Level Three Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelThreeIdentifier()
   * @generated
   * @ordered
   */
  protected String levelThreeIdentifier = LEVEL_THREE_IDENTIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getLevelFourIdentifier() <em>Level Four Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelFourIdentifier()
   * @generated
   * @ordered
   */
  protected static final String LEVEL_FOUR_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLevelFourIdentifier() <em>Level Four Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelFourIdentifier()
   * @generated
   * @ordered
   */
  protected String levelFourIdentifier = LEVEL_FOUR_IDENTIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getLevelFiveIdentifier() <em>Level Five Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelFiveIdentifier()
   * @generated
   * @ordered
   */
  protected static final String LEVEL_FIVE_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLevelFiveIdentifier() <em>Level Five Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelFiveIdentifier()
   * @generated
   * @ordered
   */
  protected String levelFiveIdentifier = LEVEL_FIVE_IDENTIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getLevelSixIdentifier() <em>Level Six Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelSixIdentifier()
   * @generated
   * @ordered
   */
  protected static final String LEVEL_SIX_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLevelSixIdentifier() <em>Level Six Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevelSixIdentifier()
   * @generated
   * @ordered
   */
  protected String levelSixIdentifier = LEVEL_SIX_IDENTIFIER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BillLevelIdentificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getBillLevelIdentification();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLevelOneIdentifier()
  {
    return levelOneIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLevelOneIdentifier(String newLevelOneIdentifier)
  {
    String oldLevelOneIdentifier = levelOneIdentifier;
    levelOneIdentifier = newLevelOneIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_ONE_IDENTIFIER, oldLevelOneIdentifier, levelOneIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLevelTwoIdentifier()
  {
    return levelTwoIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLevelTwoIdentifier(String newLevelTwoIdentifier)
  {
    String oldLevelTwoIdentifier = levelTwoIdentifier;
    levelTwoIdentifier = newLevelTwoIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_TWO_IDENTIFIER, oldLevelTwoIdentifier, levelTwoIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLevelThreeIdentifier()
  {
    return levelThreeIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLevelThreeIdentifier(String newLevelThreeIdentifier)
  {
    String oldLevelThreeIdentifier = levelThreeIdentifier;
    levelThreeIdentifier = newLevelThreeIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_THREE_IDENTIFIER, oldLevelThreeIdentifier, levelThreeIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLevelFourIdentifier()
  {
    return levelFourIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLevelFourIdentifier(String newLevelFourIdentifier)
  {
    String oldLevelFourIdentifier = levelFourIdentifier;
    levelFourIdentifier = newLevelFourIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FOUR_IDENTIFIER, oldLevelFourIdentifier, levelFourIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLevelFiveIdentifier()
  {
    return levelFiveIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLevelFiveIdentifier(String newLevelFiveIdentifier)
  {
    String oldLevelFiveIdentifier = levelFiveIdentifier;
    levelFiveIdentifier = newLevelFiveIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FIVE_IDENTIFIER, oldLevelFiveIdentifier, levelFiveIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLevelSixIdentifier()
  {
    return levelSixIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLevelSixIdentifier(String newLevelSixIdentifier)
  {
    String oldLevelSixIdentifier = levelSixIdentifier;
    levelSixIdentifier = newLevelSixIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_SIX_IDENTIFIER, oldLevelSixIdentifier, levelSixIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_ONE_IDENTIFIER:
        return getLevelOneIdentifier();
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_TWO_IDENTIFIER:
        return getLevelTwoIdentifier();
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_THREE_IDENTIFIER:
        return getLevelThreeIdentifier();
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FOUR_IDENTIFIER:
        return getLevelFourIdentifier();
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FIVE_IDENTIFIER:
        return getLevelFiveIdentifier();
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_SIX_IDENTIFIER:
        return getLevelSixIdentifier();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_ONE_IDENTIFIER:
        setLevelOneIdentifier((String)newValue);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_TWO_IDENTIFIER:
        setLevelTwoIdentifier((String)newValue);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_THREE_IDENTIFIER:
        setLevelThreeIdentifier((String)newValue);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FOUR_IDENTIFIER:
        setLevelFourIdentifier((String)newValue);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FIVE_IDENTIFIER:
        setLevelFiveIdentifier((String)newValue);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_SIX_IDENTIFIER:
        setLevelSixIdentifier((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_ONE_IDENTIFIER:
        setLevelOneIdentifier(LEVEL_ONE_IDENTIFIER_EDEFAULT);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_TWO_IDENTIFIER:
        setLevelTwoIdentifier(LEVEL_TWO_IDENTIFIER_EDEFAULT);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_THREE_IDENTIFIER:
        setLevelThreeIdentifier(LEVEL_THREE_IDENTIFIER_EDEFAULT);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FOUR_IDENTIFIER:
        setLevelFourIdentifier(LEVEL_FOUR_IDENTIFIER_EDEFAULT);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FIVE_IDENTIFIER:
        setLevelFiveIdentifier(LEVEL_FIVE_IDENTIFIER_EDEFAULT);
        return;
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_SIX_IDENTIFIER:
        setLevelSixIdentifier(LEVEL_SIX_IDENTIFIER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_ONE_IDENTIFIER:
        return LEVEL_ONE_IDENTIFIER_EDEFAULT == null ? levelOneIdentifier != null : !LEVEL_ONE_IDENTIFIER_EDEFAULT.equals(levelOneIdentifier);
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_TWO_IDENTIFIER:
        return LEVEL_TWO_IDENTIFIER_EDEFAULT == null ? levelTwoIdentifier != null : !LEVEL_TWO_IDENTIFIER_EDEFAULT.equals(levelTwoIdentifier);
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_THREE_IDENTIFIER:
        return LEVEL_THREE_IDENTIFIER_EDEFAULT == null ? levelThreeIdentifier != null : !LEVEL_THREE_IDENTIFIER_EDEFAULT.equals(levelThreeIdentifier);
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FOUR_IDENTIFIER:
        return LEVEL_FOUR_IDENTIFIER_EDEFAULT == null ? levelFourIdentifier != null : !LEVEL_FOUR_IDENTIFIER_EDEFAULT.equals(levelFourIdentifier);
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_FIVE_IDENTIFIER:
        return LEVEL_FIVE_IDENTIFIER_EDEFAULT == null ? levelFiveIdentifier != null : !LEVEL_FIVE_IDENTIFIER_EDEFAULT.equals(levelFiveIdentifier);
      case EdilangPackage.BILL_LEVEL_IDENTIFICATION__LEVEL_SIX_IDENTIFIER:
        return LEVEL_SIX_IDENTIFIER_EDEFAULT == null ? levelSixIdentifier != null : !LEVEL_SIX_IDENTIFIER_EDEFAULT.equals(levelSixIdentifier);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (levelOneIdentifier: ");
    result.append(levelOneIdentifier);
    result.append(", levelTwoIdentifier: ");
    result.append(levelTwoIdentifier);
    result.append(", levelThreeIdentifier: ");
    result.append(levelThreeIdentifier);
    result.append(", levelFourIdentifier: ");
    result.append(levelFourIdentifier);
    result.append(", levelFiveIdentifier: ");
    result.append(levelFiveIdentifier);
    result.append(", levelSixIdentifier: ");
    result.append(levelSixIdentifier);
    result.append(')');
    return result.toString();
  }

} //BillLevelIdentificationImpl
