/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.ClinicalInformationDetail;
import io.thlaegler.edifact.edilang.EdilangPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Clinical Information Detail</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.ClinicalInformationDetailImpl#getClinicalInformationDescriptionIdentifier <em>Clinical Information Description Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.ClinicalInformationDetailImpl#getCodeListIdentificationCode <em>Code List Identification Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.ClinicalInformationDetailImpl#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.ClinicalInformationDetailImpl#getClinicalInformationDescription <em>Clinical Information Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClinicalInformationDetailImpl extends MinimalEObjectImpl.Container implements ClinicalInformationDetail
{
  /**
   * The default value of the '{@link #getClinicalInformationDescriptionIdentifier() <em>Clinical Information Description Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClinicalInformationDescriptionIdentifier()
   * @generated
   * @ordered
   */
  protected static final String CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getClinicalInformationDescriptionIdentifier() <em>Clinical Information Description Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClinicalInformationDescriptionIdentifier()
   * @generated
   * @ordered
   */
  protected String clinicalInformationDescriptionIdentifier = CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListIdentificationCode() <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_IDENTIFICATION_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListIdentificationCode() <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode()
   * @generated
   * @ordered
   */
  protected String codeListIdentificationCode = CODE_LIST_IDENTIFICATION_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListResponsibleAgencyCode() <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListResponsibleAgencyCode() <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   * @ordered
   */
  protected String codeListResponsibleAgencyCode = CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getClinicalInformationDescription() <em>Clinical Information Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClinicalInformationDescription()
   * @generated
   * @ordered
   */
  protected static final String CLINICAL_INFORMATION_DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getClinicalInformationDescription() <em>Clinical Information Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClinicalInformationDescription()
   * @generated
   * @ordered
   */
  protected String clinicalInformationDescription = CLINICAL_INFORMATION_DESCRIPTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClinicalInformationDetailImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getClinicalInformationDetail();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getClinicalInformationDescriptionIdentifier()
  {
    return clinicalInformationDescriptionIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClinicalInformationDescriptionIdentifier(String newClinicalInformationDescriptionIdentifier)
  {
    String oldClinicalInformationDescriptionIdentifier = clinicalInformationDescriptionIdentifier;
    clinicalInformationDescriptionIdentifier = newClinicalInformationDescriptionIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER, oldClinicalInformationDescriptionIdentifier, clinicalInformationDescriptionIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListIdentificationCode()
  {
    return codeListIdentificationCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListIdentificationCode(String newCodeListIdentificationCode)
  {
    String oldCodeListIdentificationCode = codeListIdentificationCode;
    codeListIdentificationCode = newCodeListIdentificationCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_IDENTIFICATION_CODE, oldCodeListIdentificationCode, codeListIdentificationCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListResponsibleAgencyCode()
  {
    return codeListResponsibleAgencyCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListResponsibleAgencyCode(String newCodeListResponsibleAgencyCode)
  {
    String oldCodeListResponsibleAgencyCode = codeListResponsibleAgencyCode;
    codeListResponsibleAgencyCode = newCodeListResponsibleAgencyCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE, oldCodeListResponsibleAgencyCode, codeListResponsibleAgencyCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getClinicalInformationDescription()
  {
    return clinicalInformationDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClinicalInformationDescription(String newClinicalInformationDescription)
  {
    String oldClinicalInformationDescription = clinicalInformationDescription;
    clinicalInformationDescription = newClinicalInformationDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION, oldClinicalInformationDescription, clinicalInformationDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER:
        return getClinicalInformationDescriptionIdentifier();
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_IDENTIFICATION_CODE:
        return getCodeListIdentificationCode();
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        return getCodeListResponsibleAgencyCode();
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION:
        return getClinicalInformationDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER:
        setClinicalInformationDescriptionIdentifier((String)newValue);
        return;
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_IDENTIFICATION_CODE:
        setCodeListIdentificationCode((String)newValue);
        return;
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        setCodeListResponsibleAgencyCode((String)newValue);
        return;
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION:
        setClinicalInformationDescription((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER:
        setClinicalInformationDescriptionIdentifier(CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER_EDEFAULT);
        return;
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_IDENTIFICATION_CODE:
        setCodeListIdentificationCode(CODE_LIST_IDENTIFICATION_CODE_EDEFAULT);
        return;
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        setCodeListResponsibleAgencyCode(CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT);
        return;
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION:
        setClinicalInformationDescription(CLINICAL_INFORMATION_DESCRIPTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER:
        return CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER_EDEFAULT == null ? clinicalInformationDescriptionIdentifier != null : !CLINICAL_INFORMATION_DESCRIPTION_IDENTIFIER_EDEFAULT.equals(clinicalInformationDescriptionIdentifier);
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_IDENTIFICATION_CODE:
        return CODE_LIST_IDENTIFICATION_CODE_EDEFAULT == null ? codeListIdentificationCode != null : !CODE_LIST_IDENTIFICATION_CODE_EDEFAULT.equals(codeListIdentificationCode);
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        return CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT == null ? codeListResponsibleAgencyCode != null : !CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT.equals(codeListResponsibleAgencyCode);
      case EdilangPackage.CLINICAL_INFORMATION_DETAIL__CLINICAL_INFORMATION_DESCRIPTION:
        return CLINICAL_INFORMATION_DESCRIPTION_EDEFAULT == null ? clinicalInformationDescription != null : !CLINICAL_INFORMATION_DESCRIPTION_EDEFAULT.equals(clinicalInformationDescription);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (clinicalInformationDescriptionIdentifier: ");
    result.append(clinicalInformationDescriptionIdentifier);
    result.append(", codeListIdentificationCode: ");
    result.append(codeListIdentificationCode);
    result.append(", codeListResponsibleAgencyCode: ");
    result.append(codeListResponsibleAgencyCode);
    result.append(", clinicalInformationDescription: ");
    result.append(clinicalInformationDescription);
    result.append(')');
    return result.toString();
  }

} //ClinicalInformationDetailImpl
