/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.DateTimePeriod;
import io.thlaegler.edifact.edilang.EdilangPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Date Time Period</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.DateTimePeriodImpl#getDateTimePeriodFunctionCodeQualifier <em>Date Time Period Function Code Qualifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.DateTimePeriodImpl#getDateTimePeriodValue <em>Date Time Period Value</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.DateTimePeriodImpl#getDateTimePeriodFormatCode <em>Date Time Period Format Code</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DateTimePeriodImpl extends AbstractEdiFunctionImpl implements DateTimePeriod
{
  /**
   * The default value of the '{@link #getDateTimePeriodFunctionCodeQualifier() <em>Date Time Period Function Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateTimePeriodFunctionCodeQualifier()
   * @generated
   * @ordered
   */
  protected static final String DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDateTimePeriodFunctionCodeQualifier() <em>Date Time Period Function Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateTimePeriodFunctionCodeQualifier()
   * @generated
   * @ordered
   */
  protected String dateTimePeriodFunctionCodeQualifier = DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getDateTimePeriodValue() <em>Date Time Period Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateTimePeriodValue()
   * @generated
   * @ordered
   */
  protected static final String DATE_TIME_PERIOD_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDateTimePeriodValue() <em>Date Time Period Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateTimePeriodValue()
   * @generated
   * @ordered
   */
  protected String dateTimePeriodValue = DATE_TIME_PERIOD_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getDateTimePeriodFormatCode() <em>Date Time Period Format Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateTimePeriodFormatCode()
   * @generated
   * @ordered
   */
  protected static final String DATE_TIME_PERIOD_FORMAT_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDateTimePeriodFormatCode() <em>Date Time Period Format Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateTimePeriodFormatCode()
   * @generated
   * @ordered
   */
  protected String dateTimePeriodFormatCode = DATE_TIME_PERIOD_FORMAT_CODE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DateTimePeriodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getDateTimePeriod();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDateTimePeriodFunctionCodeQualifier()
  {
    return dateTimePeriodFunctionCodeQualifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDateTimePeriodFunctionCodeQualifier(String newDateTimePeriodFunctionCodeQualifier)
  {
    String oldDateTimePeriodFunctionCodeQualifier = dateTimePeriodFunctionCodeQualifier;
    dateTimePeriodFunctionCodeQualifier = newDateTimePeriodFunctionCodeQualifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER, oldDateTimePeriodFunctionCodeQualifier, dateTimePeriodFunctionCodeQualifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDateTimePeriodValue()
  {
    return dateTimePeriodValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDateTimePeriodValue(String newDateTimePeriodValue)
  {
    String oldDateTimePeriodValue = dateTimePeriodValue;
    dateTimePeriodValue = newDateTimePeriodValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_VALUE, oldDateTimePeriodValue, dateTimePeriodValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDateTimePeriodFormatCode()
  {
    return dateTimePeriodFormatCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDateTimePeriodFormatCode(String newDateTimePeriodFormatCode)
  {
    String oldDateTimePeriodFormatCode = dateTimePeriodFormatCode;
    dateTimePeriodFormatCode = newDateTimePeriodFormatCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FORMAT_CODE, oldDateTimePeriodFormatCode, dateTimePeriodFormatCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER:
        return getDateTimePeriodFunctionCodeQualifier();
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_VALUE:
        return getDateTimePeriodValue();
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FORMAT_CODE:
        return getDateTimePeriodFormatCode();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER:
        setDateTimePeriodFunctionCodeQualifier((String)newValue);
        return;
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_VALUE:
        setDateTimePeriodValue((String)newValue);
        return;
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FORMAT_CODE:
        setDateTimePeriodFormatCode((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER:
        setDateTimePeriodFunctionCodeQualifier(DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER_EDEFAULT);
        return;
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_VALUE:
        setDateTimePeriodValue(DATE_TIME_PERIOD_VALUE_EDEFAULT);
        return;
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FORMAT_CODE:
        setDateTimePeriodFormatCode(DATE_TIME_PERIOD_FORMAT_CODE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER:
        return DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER_EDEFAULT == null ? dateTimePeriodFunctionCodeQualifier != null : !DATE_TIME_PERIOD_FUNCTION_CODE_QUALIFIER_EDEFAULT.equals(dateTimePeriodFunctionCodeQualifier);
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_VALUE:
        return DATE_TIME_PERIOD_VALUE_EDEFAULT == null ? dateTimePeriodValue != null : !DATE_TIME_PERIOD_VALUE_EDEFAULT.equals(dateTimePeriodValue);
      case EdilangPackage.DATE_TIME_PERIOD__DATE_TIME_PERIOD_FORMAT_CODE:
        return DATE_TIME_PERIOD_FORMAT_CODE_EDEFAULT == null ? dateTimePeriodFormatCode != null : !DATE_TIME_PERIOD_FORMAT_CODE_EDEFAULT.equals(dateTimePeriodFormatCode);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (dateTimePeriodFunctionCodeQualifier: ");
    result.append(dateTimePeriodFunctionCodeQualifier);
    result.append(", dateTimePeriodValue: ");
    result.append(dateTimePeriodValue);
    result.append(", dateTimePeriodFormatCode: ");
    result.append(dateTimePeriodFormatCode);
    result.append(')');
    return result.toString();
  }

} //DateTimePeriodImpl
