/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class EdilangFactoryImpl extends EFactoryImpl implements EdilangFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static EdilangFactory init()
  {
    try
    {
      EdilangFactory theEdilangFactory = (EdilangFactory)EPackage.Registry.INSTANCE.getEFactory(EdilangPackage.eNS_URI);
      if (theEdilangFactory != null)
      {
        return theEdilangFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new EdilangFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EdilangFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case EdilangPackage.EDI_MODEL: return createEdiModel();
      case EdilangPackage.ABSTRACT_EDI_SEGMENT: return createAbstractEdiSegment();
      case EdilangPackage.UNA_SEGMENT: return createUNASegment();
      case EdilangPackage.UNB_SEGMENT: return createUNBSegment();
      case EdilangPackage.UNH_SEGMENT: return createUNHSegment();
      case EdilangPackage.MSG_SEGMENT: return createMSGSegment();
      case EdilangPackage.ORG_SEGMENT: return createORGSegment();
      case EdilangPackage.POC_SEGMENT: return createPOCSegment();
      case EdilangPackage.ODI_SEGMENT: return createODISegment();
      case EdilangPackage.UCI_SEGMENT: return createUCISegment();
      case EdilangPackage.PDI_SEGMENT: return createPDISegment();
      case EdilangPackage.TVL_SEGMENT: return createTVLSegment();
      case EdilangPackage.RPI_SEGMENT: return createRPISegment();
      case EdilangPackage.MOA_SEGMENT: return createMOASegment();
      case EdilangPackage.LIN_SEGMENT: return createLINSegment();
      case EdilangPackage.PRI_SEGMENT: return createPRISegment();
      case EdilangPackage.QTY_SEGMENT: return createQTYSegment();
      case EdilangPackage.CUX_SEGMENT: return createCUXSegment();
      case EdilangPackage.TAX_SEGMENT: return createTAXSegment();
      case EdilangPackage.RFF_SEGMENT: return createRFFSegment();
      case EdilangPackage.NAD_SEGMENT: return createNADSegment();
      case EdilangPackage.DTM_SEGMENT: return createDTMSegment();
      case EdilangPackage.BGM_SEGMENT: return createBGMSegment();
      case EdilangPackage.PAT_SEGMENT: return createPATSegment();
      case EdilangPackage.FTX_SEGMENT: return createFTXSegment();
      case EdilangPackage.ERC_SEGMENT: return createERCSegment();
      case EdilangPackage.CNT_SEGMENT: return createCNTSegment();
      case EdilangPackage.CTA_SEGMENT: return createCTASegment();
      case EdilangPackage.PCI_SEGMENT: return createPCISegment();
      case EdilangPackage.UNS_SEGMENT: return createUNSSegment();
      case EdilangPackage.UNT_SEGMENT: return createUNTSegment();
      case EdilangPackage.UNZ_SEGMENT: return createUNZSegment();
      case EdilangPackage.ABSTRACT_EDI_FUNCTION: return createAbstractEdiFunction();
      case EdilangPackage.PRI_FUNCTION: return createPRIFunction();
      case EdilangPackage.MESSAGE_BODY_FUNCTION: return createMessageBodyFunction();
      case EdilangPackage.MSG_FUNCTION: return createMSGFunction();
      case EdilangPackage.PRODUCT_FUNCTION: return createProductFunction();
      case EdilangPackage.SYSTEM_DETAIL_FUNCTION: return createSystemDetailFunction();
      case EdilangPackage.ORIGINATOR_FUNCTION: return createOriginatorFunction();
      case EdilangPackage.ORIGINATOR_IDENTIFICATION_FUNCTION: return createOriginatorIdentificationFunction();
      case EdilangPackage.LOCATION_FUNCTION: return createLocationFunction();
      case EdilangPackage.INTERCHANGER_FUNCTION: return createInterchangerFunction();
      case EdilangPackage.DATE_ONLY_FUNCTION: return createDateOnlyFunction();
      case EdilangPackage.DATE_AND_TIME_FUNCTION: return createDateAndTimeFunction();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EdiModel createEdiModel()
  {
    EdiModelImpl ediModel = new EdiModelImpl();
    return ediModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractEdiSegment createAbstractEdiSegment()
  {
    AbstractEdiSegmentImpl abstractEdiSegment = new AbstractEdiSegmentImpl();
    return abstractEdiSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UNASegment createUNASegment()
  {
    UNASegmentImpl unaSegment = new UNASegmentImpl();
    return unaSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UNBSegment createUNBSegment()
  {
    UNBSegmentImpl unbSegment = new UNBSegmentImpl();
    return unbSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UNHSegment createUNHSegment()
  {
    UNHSegmentImpl unhSegment = new UNHSegmentImpl();
    return unhSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MSGSegment createMSGSegment()
  {
    MSGSegmentImpl msgSegment = new MSGSegmentImpl();
    return msgSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ORGSegment createORGSegment()
  {
    ORGSegmentImpl orgSegment = new ORGSegmentImpl();
    return orgSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public POCSegment createPOCSegment()
  {
    POCSegmentImpl pocSegment = new POCSegmentImpl();
    return pocSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ODISegment createODISegment()
  {
    ODISegmentImpl odiSegment = new ODISegmentImpl();
    return odiSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UCISegment createUCISegment()
  {
    UCISegmentImpl uciSegment = new UCISegmentImpl();
    return uciSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PDISegment createPDISegment()
  {
    PDISegmentImpl pdiSegment = new PDISegmentImpl();
    return pdiSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TVLSegment createTVLSegment()
  {
    TVLSegmentImpl tvlSegment = new TVLSegmentImpl();
    return tvlSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RPISegment createRPISegment()
  {
    RPISegmentImpl rpiSegment = new RPISegmentImpl();
    return rpiSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MOASegment createMOASegment()
  {
    MOASegmentImpl moaSegment = new MOASegmentImpl();
    return moaSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LINSegment createLINSegment()
  {
    LINSegmentImpl linSegment = new LINSegmentImpl();
    return linSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PRISegment createPRISegment()
  {
    PRISegmentImpl priSegment = new PRISegmentImpl();
    return priSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QTYSegment createQTYSegment()
  {
    QTYSegmentImpl qtySegment = new QTYSegmentImpl();
    return qtySegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CUXSegment createCUXSegment()
  {
    CUXSegmentImpl cuxSegment = new CUXSegmentImpl();
    return cuxSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TAXSegment createTAXSegment()
  {
    TAXSegmentImpl taxSegment = new TAXSegmentImpl();
    return taxSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RFFSegment createRFFSegment()
  {
    RFFSegmentImpl rffSegment = new RFFSegmentImpl();
    return rffSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NADSegment createNADSegment()
  {
    NADSegmentImpl nadSegment = new NADSegmentImpl();
    return nadSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DTMSegment createDTMSegment()
  {
    DTMSegmentImpl dtmSegment = new DTMSegmentImpl();
    return dtmSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BGMSegment createBGMSegment()
  {
    BGMSegmentImpl bgmSegment = new BGMSegmentImpl();
    return bgmSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PATSegment createPATSegment()
  {
    PATSegmentImpl patSegment = new PATSegmentImpl();
    return patSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FTXSegment createFTXSegment()
  {
    FTXSegmentImpl ftxSegment = new FTXSegmentImpl();
    return ftxSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ERCSegment createERCSegment()
  {
    ERCSegmentImpl ercSegment = new ERCSegmentImpl();
    return ercSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CNTSegment createCNTSegment()
  {
    CNTSegmentImpl cntSegment = new CNTSegmentImpl();
    return cntSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CTASegment createCTASegment()
  {
    CTASegmentImpl ctaSegment = new CTASegmentImpl();
    return ctaSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PCISegment createPCISegment()
  {
    PCISegmentImpl pciSegment = new PCISegmentImpl();
    return pciSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UNSSegment createUNSSegment()
  {
    UNSSegmentImpl unsSegment = new UNSSegmentImpl();
    return unsSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UNTSegment createUNTSegment()
  {
    UNTSegmentImpl untSegment = new UNTSegmentImpl();
    return untSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UNZSegment createUNZSegment()
  {
    UNZSegmentImpl unzSegment = new UNZSegmentImpl();
    return unzSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractEdiFunction createAbstractEdiFunction()
  {
    AbstractEdiFunctionImpl abstractEdiFunction = new AbstractEdiFunctionImpl();
    return abstractEdiFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PRIFunction createPRIFunction()
  {
    PRIFunctionImpl priFunction = new PRIFunctionImpl();
    return priFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MessageBodyFunction createMessageBodyFunction()
  {
    MessageBodyFunctionImpl messageBodyFunction = new MessageBodyFunctionImpl();
    return messageBodyFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MSGFunction createMSGFunction()
  {
    MSGFunctionImpl msgFunction = new MSGFunctionImpl();
    return msgFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProductFunction createProductFunction()
  {
    ProductFunctionImpl productFunction = new ProductFunctionImpl();
    return productFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SystemDetailFunction createSystemDetailFunction()
  {
    SystemDetailFunctionImpl systemDetailFunction = new SystemDetailFunctionImpl();
    return systemDetailFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OriginatorFunction createOriginatorFunction()
  {
    OriginatorFunctionImpl originatorFunction = new OriginatorFunctionImpl();
    return originatorFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OriginatorIdentificationFunction createOriginatorIdentificationFunction()
  {
    OriginatorIdentificationFunctionImpl originatorIdentificationFunction = new OriginatorIdentificationFunctionImpl();
    return originatorIdentificationFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LocationFunction createLocationFunction()
  {
    LocationFunctionImpl locationFunction = new LocationFunctionImpl();
    return locationFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InterchangerFunction createInterchangerFunction()
  {
    InterchangerFunctionImpl interchangerFunction = new InterchangerFunctionImpl();
    return interchangerFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DateOnlyFunction createDateOnlyFunction()
  {
    DateOnlyFunctionImpl dateOnlyFunction = new DateOnlyFunctionImpl();
    return dateOnlyFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DateAndTimeFunction createDateAndTimeFunction()
  {
    DateAndTimeFunctionImpl dateAndTimeFunction = new DateAndTimeFunctionImpl();
    return dateAndTimeFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EdilangPackage getEdilangPackage()
  {
    return (EdilangPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static EdilangPackage getPackage()
  {
    return EdilangPackage.eINSTANCE;
  }

} //EdilangFactoryImpl
