/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.ApplicationErrorDetail;
import io.thlaegler.edifact.edilang.ERCSegment;
import io.thlaegler.edifact.edilang.EdilangPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>ERC Segment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.ERCSegmentImpl#getApplicationErrorDetails <em>Application Error Details</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ERCSegmentImpl extends AbstractEdiSegmentImpl implements ERCSegment
{
  /**
   * The cached value of the '{@link #getApplicationErrorDetails() <em>Application Error Details</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApplicationErrorDetails()
   * @generated
   * @ordered
   */
  protected EList<ApplicationErrorDetail> applicationErrorDetails;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ERCSegmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getERCSegment();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ApplicationErrorDetail> getApplicationErrorDetails()
  {
    if (applicationErrorDetails == null)
    {
      applicationErrorDetails = new EObjectContainmentEList<ApplicationErrorDetail>(ApplicationErrorDetail.class, this, EdilangPackage.ERC_SEGMENT__APPLICATION_ERROR_DETAILS);
    }
    return applicationErrorDetails;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EdilangPackage.ERC_SEGMENT__APPLICATION_ERROR_DETAILS:
        return ((InternalEList<?>)getApplicationErrorDetails()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.ERC_SEGMENT__APPLICATION_ERROR_DETAILS:
        return getApplicationErrorDetails();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.ERC_SEGMENT__APPLICATION_ERROR_DETAILS:
        getApplicationErrorDetails().clear();
        getApplicationErrorDetails().addAll((Collection<? extends ApplicationErrorDetail>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.ERC_SEGMENT__APPLICATION_ERROR_DETAILS:
        getApplicationErrorDetails().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.ERC_SEGMENT__APPLICATION_ERROR_DETAILS:
        return applicationErrorDetails != null && !applicationErrorDetails.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ERCSegmentImpl
