/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.EdilangPackage;
import io.thlaegler.edifact.edilang.InformationRequest;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Information Request</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.InformationRequestImpl#getRequestedInformationDescriptionCode <em>Requested Information Description Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.InformationRequestImpl#getCodeListIdentificationCode <em>Code List Identification Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.InformationRequestImpl#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.InformationRequestImpl#getRequestedInformationDescription <em>Requested Information Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InformationRequestImpl extends AbstractEdiFunctionImpl implements InformationRequest
{
  /**
   * The default value of the '{@link #getRequestedInformationDescriptionCode() <em>Requested Information Description Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequestedInformationDescriptionCode()
   * @generated
   * @ordered
   */
  protected static final String REQUESTED_INFORMATION_DESCRIPTION_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRequestedInformationDescriptionCode() <em>Requested Information Description Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequestedInformationDescriptionCode()
   * @generated
   * @ordered
   */
  protected String requestedInformationDescriptionCode = REQUESTED_INFORMATION_DESCRIPTION_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListIdentificationCode() <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_IDENTIFICATION_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListIdentificationCode() <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode()
   * @generated
   * @ordered
   */
  protected String codeListIdentificationCode = CODE_LIST_IDENTIFICATION_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListResponsibleAgencyCode() <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListResponsibleAgencyCode() <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   * @ordered
   */
  protected String codeListResponsibleAgencyCode = CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getRequestedInformationDescription() <em>Requested Information Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequestedInformationDescription()
   * @generated
   * @ordered
   */
  protected static final String REQUESTED_INFORMATION_DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRequestedInformationDescription() <em>Requested Information Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequestedInformationDescription()
   * @generated
   * @ordered
   */
  protected String requestedInformationDescription = REQUESTED_INFORMATION_DESCRIPTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InformationRequestImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getInformationRequest();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRequestedInformationDescriptionCode()
  {
    return requestedInformationDescriptionCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRequestedInformationDescriptionCode(String newRequestedInformationDescriptionCode)
  {
    String oldRequestedInformationDescriptionCode = requestedInformationDescriptionCode;
    requestedInformationDescriptionCode = newRequestedInformationDescriptionCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION_CODE, oldRequestedInformationDescriptionCode, requestedInformationDescriptionCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListIdentificationCode()
  {
    return codeListIdentificationCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListIdentificationCode(String newCodeListIdentificationCode)
  {
    String oldCodeListIdentificationCode = codeListIdentificationCode;
    codeListIdentificationCode = newCodeListIdentificationCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.INFORMATION_REQUEST__CODE_LIST_IDENTIFICATION_CODE, oldCodeListIdentificationCode, codeListIdentificationCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListResponsibleAgencyCode()
  {
    return codeListResponsibleAgencyCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListResponsibleAgencyCode(String newCodeListResponsibleAgencyCode)
  {
    String oldCodeListResponsibleAgencyCode = codeListResponsibleAgencyCode;
    codeListResponsibleAgencyCode = newCodeListResponsibleAgencyCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.INFORMATION_REQUEST__CODE_LIST_RESPONSIBLE_AGENCY_CODE, oldCodeListResponsibleAgencyCode, codeListResponsibleAgencyCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRequestedInformationDescription()
  {
    return requestedInformationDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRequestedInformationDescription(String newRequestedInformationDescription)
  {
    String oldRequestedInformationDescription = requestedInformationDescription;
    requestedInformationDescription = newRequestedInformationDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION, oldRequestedInformationDescription, requestedInformationDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION_CODE:
        return getRequestedInformationDescriptionCode();
      case EdilangPackage.INFORMATION_REQUEST__CODE_LIST_IDENTIFICATION_CODE:
        return getCodeListIdentificationCode();
      case EdilangPackage.INFORMATION_REQUEST__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        return getCodeListResponsibleAgencyCode();
      case EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION:
        return getRequestedInformationDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION_CODE:
        setRequestedInformationDescriptionCode((String)newValue);
        return;
      case EdilangPackage.INFORMATION_REQUEST__CODE_LIST_IDENTIFICATION_CODE:
        setCodeListIdentificationCode((String)newValue);
        return;
      case EdilangPackage.INFORMATION_REQUEST__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        setCodeListResponsibleAgencyCode((String)newValue);
        return;
      case EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION:
        setRequestedInformationDescription((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION_CODE:
        setRequestedInformationDescriptionCode(REQUESTED_INFORMATION_DESCRIPTION_CODE_EDEFAULT);
        return;
      case EdilangPackage.INFORMATION_REQUEST__CODE_LIST_IDENTIFICATION_CODE:
        setCodeListIdentificationCode(CODE_LIST_IDENTIFICATION_CODE_EDEFAULT);
        return;
      case EdilangPackage.INFORMATION_REQUEST__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        setCodeListResponsibleAgencyCode(CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT);
        return;
      case EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION:
        setRequestedInformationDescription(REQUESTED_INFORMATION_DESCRIPTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION_CODE:
        return REQUESTED_INFORMATION_DESCRIPTION_CODE_EDEFAULT == null ? requestedInformationDescriptionCode != null : !REQUESTED_INFORMATION_DESCRIPTION_CODE_EDEFAULT.equals(requestedInformationDescriptionCode);
      case EdilangPackage.INFORMATION_REQUEST__CODE_LIST_IDENTIFICATION_CODE:
        return CODE_LIST_IDENTIFICATION_CODE_EDEFAULT == null ? codeListIdentificationCode != null : !CODE_LIST_IDENTIFICATION_CODE_EDEFAULT.equals(codeListIdentificationCode);
      case EdilangPackage.INFORMATION_REQUEST__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        return CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT == null ? codeListResponsibleAgencyCode != null : !CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT.equals(codeListResponsibleAgencyCode);
      case EdilangPackage.INFORMATION_REQUEST__REQUESTED_INFORMATION_DESCRIPTION:
        return REQUESTED_INFORMATION_DESCRIPTION_EDEFAULT == null ? requestedInformationDescription != null : !REQUESTED_INFORMATION_DESCRIPTION_EDEFAULT.equals(requestedInformationDescription);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (requestedInformationDescriptionCode: ");
    result.append(requestedInformationDescriptionCode);
    result.append(", codeListIdentificationCode: ");
    result.append(codeListIdentificationCode);
    result.append(", codeListResponsibleAgencyCode: ");
    result.append(codeListResponsibleAgencyCode);
    result.append(", requestedInformationDescription: ");
    result.append(requestedInformationDescription);
    result.append(')');
    return result.toString();
  }

} //InformationRequestImpl
