/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.EdilangPackage;
import io.thlaegler.edifact.edilang.Location;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Location</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.LocationImpl#getLocationIdentifier <em>Location Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.LocationImpl#getLocationName <em>Location Name</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.LocationImpl#getCountryIdentifier <em>Country Identifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.LocationImpl#getLocationFunctionCodeQualifier <em>Location Function Code Qualifier</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LocationImpl extends AbstractEdiFunctionImpl implements Location
{
  /**
   * The default value of the '{@link #getLocationIdentifier() <em>Location Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationIdentifier()
   * @generated
   * @ordered
   */
  protected static final String LOCATION_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLocationIdentifier() <em>Location Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationIdentifier()
   * @generated
   * @ordered
   */
  protected String locationIdentifier = LOCATION_IDENTIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getLocationName() <em>Location Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationName()
   * @generated
   * @ordered
   */
  protected static final String LOCATION_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLocationName() <em>Location Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationName()
   * @generated
   * @ordered
   */
  protected String locationName = LOCATION_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getCountryIdentifier() <em>Country Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCountryIdentifier()
   * @generated
   * @ordered
   */
  protected static final String COUNTRY_IDENTIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCountryIdentifier() <em>Country Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCountryIdentifier()
   * @generated
   * @ordered
   */
  protected String countryIdentifier = COUNTRY_IDENTIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getLocationFunctionCodeQualifier() <em>Location Function Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationFunctionCodeQualifier()
   * @generated
   * @ordered
   */
  protected static final String LOCATION_FUNCTION_CODE_QUALIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLocationFunctionCodeQualifier() <em>Location Function Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationFunctionCodeQualifier()
   * @generated
   * @ordered
   */
  protected String locationFunctionCodeQualifier = LOCATION_FUNCTION_CODE_QUALIFIER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LocationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getLocation();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLocationIdentifier()
  {
    return locationIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocationIdentifier(String newLocationIdentifier)
  {
    String oldLocationIdentifier = locationIdentifier;
    locationIdentifier = newLocationIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.LOCATION__LOCATION_IDENTIFIER, oldLocationIdentifier, locationIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLocationName()
  {
    return locationName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocationName(String newLocationName)
  {
    String oldLocationName = locationName;
    locationName = newLocationName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.LOCATION__LOCATION_NAME, oldLocationName, locationName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCountryIdentifier()
  {
    return countryIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCountryIdentifier(String newCountryIdentifier)
  {
    String oldCountryIdentifier = countryIdentifier;
    countryIdentifier = newCountryIdentifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.LOCATION__COUNTRY_IDENTIFIER, oldCountryIdentifier, countryIdentifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLocationFunctionCodeQualifier()
  {
    return locationFunctionCodeQualifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocationFunctionCodeQualifier(String newLocationFunctionCodeQualifier)
  {
    String oldLocationFunctionCodeQualifier = locationFunctionCodeQualifier;
    locationFunctionCodeQualifier = newLocationFunctionCodeQualifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.LOCATION__LOCATION_FUNCTION_CODE_QUALIFIER, oldLocationFunctionCodeQualifier, locationFunctionCodeQualifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.LOCATION__LOCATION_IDENTIFIER:
        return getLocationIdentifier();
      case EdilangPackage.LOCATION__LOCATION_NAME:
        return getLocationName();
      case EdilangPackage.LOCATION__COUNTRY_IDENTIFIER:
        return getCountryIdentifier();
      case EdilangPackage.LOCATION__LOCATION_FUNCTION_CODE_QUALIFIER:
        return getLocationFunctionCodeQualifier();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.LOCATION__LOCATION_IDENTIFIER:
        setLocationIdentifier((String)newValue);
        return;
      case EdilangPackage.LOCATION__LOCATION_NAME:
        setLocationName((String)newValue);
        return;
      case EdilangPackage.LOCATION__COUNTRY_IDENTIFIER:
        setCountryIdentifier((String)newValue);
        return;
      case EdilangPackage.LOCATION__LOCATION_FUNCTION_CODE_QUALIFIER:
        setLocationFunctionCodeQualifier((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.LOCATION__LOCATION_IDENTIFIER:
        setLocationIdentifier(LOCATION_IDENTIFIER_EDEFAULT);
        return;
      case EdilangPackage.LOCATION__LOCATION_NAME:
        setLocationName(LOCATION_NAME_EDEFAULT);
        return;
      case EdilangPackage.LOCATION__COUNTRY_IDENTIFIER:
        setCountryIdentifier(COUNTRY_IDENTIFIER_EDEFAULT);
        return;
      case EdilangPackage.LOCATION__LOCATION_FUNCTION_CODE_QUALIFIER:
        setLocationFunctionCodeQualifier(LOCATION_FUNCTION_CODE_QUALIFIER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.LOCATION__LOCATION_IDENTIFIER:
        return LOCATION_IDENTIFIER_EDEFAULT == null ? locationIdentifier != null : !LOCATION_IDENTIFIER_EDEFAULT.equals(locationIdentifier);
      case EdilangPackage.LOCATION__LOCATION_NAME:
        return LOCATION_NAME_EDEFAULT == null ? locationName != null : !LOCATION_NAME_EDEFAULT.equals(locationName);
      case EdilangPackage.LOCATION__COUNTRY_IDENTIFIER:
        return COUNTRY_IDENTIFIER_EDEFAULT == null ? countryIdentifier != null : !COUNTRY_IDENTIFIER_EDEFAULT.equals(countryIdentifier);
      case EdilangPackage.LOCATION__LOCATION_FUNCTION_CODE_QUALIFIER:
        return LOCATION_FUNCTION_CODE_QUALIFIER_EDEFAULT == null ? locationFunctionCodeQualifier != null : !LOCATION_FUNCTION_CODE_QUALIFIER_EDEFAULT.equals(locationFunctionCodeQualifier);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (locationIdentifier: ");
    result.append(locationIdentifier);
    result.append(", locationName: ");
    result.append(locationName);
    result.append(", countryIdentifier: ");
    result.append(countryIdentifier);
    result.append(", locationFunctionCodeQualifier: ");
    result.append(locationFunctionCodeQualifier);
    result.append(')');
    return result.toString();
  }

} //LocationImpl
