/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.EdilangPackage;
import io.thlaegler.edifact.edilang.MonetaryAmountFunction;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Monetary Amount Function</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.MonetaryAmountFunctionImpl#getMonetaryAmountFunctionDescriptionCode <em>Monetary Amount Function Description Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.MonetaryAmountFunctionImpl#getCodeListIdentificationCode <em>Code List Identification Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.MonetaryAmountFunctionImpl#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.MonetaryAmountFunctionImpl#getMonetaryAmountFunctionDescription <em>Monetary Amount Function Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MonetaryAmountFunctionImpl extends AbstractEdiFunctionImpl implements MonetaryAmountFunction
{
  /**
   * The default value of the '{@link #getMonetaryAmountFunctionDescriptionCode() <em>Monetary Amount Function Description Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMonetaryAmountFunctionDescriptionCode()
   * @generated
   * @ordered
   */
  protected static final String MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMonetaryAmountFunctionDescriptionCode() <em>Monetary Amount Function Description Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMonetaryAmountFunctionDescriptionCode()
   * @generated
   * @ordered
   */
  protected String monetaryAmountFunctionDescriptionCode = MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListIdentificationCode() <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_IDENTIFICATION_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListIdentificationCode() <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode()
   * @generated
   * @ordered
   */
  protected String codeListIdentificationCode = CODE_LIST_IDENTIFICATION_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListResponsibleAgencyCode() <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListResponsibleAgencyCode() <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   * @ordered
   */
  protected String codeListResponsibleAgencyCode = CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getMonetaryAmountFunctionDescription() <em>Monetary Amount Function Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMonetaryAmountFunctionDescription()
   * @generated
   * @ordered
   */
  protected static final String MONETARY_AMOUNT_FUNCTION_DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMonetaryAmountFunctionDescription() <em>Monetary Amount Function Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMonetaryAmountFunctionDescription()
   * @generated
   * @ordered
   */
  protected String monetaryAmountFunctionDescription = MONETARY_AMOUNT_FUNCTION_DESCRIPTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MonetaryAmountFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getMonetaryAmountFunction();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMonetaryAmountFunctionDescriptionCode()
  {
    return monetaryAmountFunctionDescriptionCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMonetaryAmountFunctionDescriptionCode(String newMonetaryAmountFunctionDescriptionCode)
  {
    String oldMonetaryAmountFunctionDescriptionCode = monetaryAmountFunctionDescriptionCode;
    monetaryAmountFunctionDescriptionCode = newMonetaryAmountFunctionDescriptionCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE, oldMonetaryAmountFunctionDescriptionCode, monetaryAmountFunctionDescriptionCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListIdentificationCode()
  {
    return codeListIdentificationCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListIdentificationCode(String newCodeListIdentificationCode)
  {
    String oldCodeListIdentificationCode = codeListIdentificationCode;
    codeListIdentificationCode = newCodeListIdentificationCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_IDENTIFICATION_CODE, oldCodeListIdentificationCode, codeListIdentificationCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListResponsibleAgencyCode()
  {
    return codeListResponsibleAgencyCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListResponsibleAgencyCode(String newCodeListResponsibleAgencyCode)
  {
    String oldCodeListResponsibleAgencyCode = codeListResponsibleAgencyCode;
    codeListResponsibleAgencyCode = newCodeListResponsibleAgencyCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_RESPONSIBLE_AGENCY_CODE, oldCodeListResponsibleAgencyCode, codeListResponsibleAgencyCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMonetaryAmountFunctionDescription()
  {
    return monetaryAmountFunctionDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMonetaryAmountFunctionDescription(String newMonetaryAmountFunctionDescription)
  {
    String oldMonetaryAmountFunctionDescription = monetaryAmountFunctionDescription;
    monetaryAmountFunctionDescription = newMonetaryAmountFunctionDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION, oldMonetaryAmountFunctionDescription, monetaryAmountFunctionDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE:
        return getMonetaryAmountFunctionDescriptionCode();
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_IDENTIFICATION_CODE:
        return getCodeListIdentificationCode();
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        return getCodeListResponsibleAgencyCode();
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION:
        return getMonetaryAmountFunctionDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE:
        setMonetaryAmountFunctionDescriptionCode((String)newValue);
        return;
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_IDENTIFICATION_CODE:
        setCodeListIdentificationCode((String)newValue);
        return;
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        setCodeListResponsibleAgencyCode((String)newValue);
        return;
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION:
        setMonetaryAmountFunctionDescription((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE:
        setMonetaryAmountFunctionDescriptionCode(MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE_EDEFAULT);
        return;
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_IDENTIFICATION_CODE:
        setCodeListIdentificationCode(CODE_LIST_IDENTIFICATION_CODE_EDEFAULT);
        return;
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        setCodeListResponsibleAgencyCode(CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT);
        return;
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION:
        setMonetaryAmountFunctionDescription(MONETARY_AMOUNT_FUNCTION_DESCRIPTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE:
        return MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE_EDEFAULT == null ? monetaryAmountFunctionDescriptionCode != null : !MONETARY_AMOUNT_FUNCTION_DESCRIPTION_CODE_EDEFAULT.equals(monetaryAmountFunctionDescriptionCode);
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_IDENTIFICATION_CODE:
        return CODE_LIST_IDENTIFICATION_CODE_EDEFAULT == null ? codeListIdentificationCode != null : !CODE_LIST_IDENTIFICATION_CODE_EDEFAULT.equals(codeListIdentificationCode);
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        return CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT == null ? codeListResponsibleAgencyCode != null : !CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT.equals(codeListResponsibleAgencyCode);
      case EdilangPackage.MONETARY_AMOUNT_FUNCTION__MONETARY_AMOUNT_FUNCTION_DESCRIPTION:
        return MONETARY_AMOUNT_FUNCTION_DESCRIPTION_EDEFAULT == null ? monetaryAmountFunctionDescription != null : !MONETARY_AMOUNT_FUNCTION_DESCRIPTION_EDEFAULT.equals(monetaryAmountFunctionDescription);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (monetaryAmountFunctionDescriptionCode: ");
    result.append(monetaryAmountFunctionDescriptionCode);
    result.append(", codeListIdentificationCode: ");
    result.append(codeListIdentificationCode);
    result.append(", codeListResponsibleAgencyCode: ");
    result.append(codeListResponsibleAgencyCode);
    result.append(", monetaryAmountFunctionDescription: ");
    result.append(monetaryAmountFunctionDescription);
    result.append(')');
    return result.toString();
  }

} //MonetaryAmountFunctionImpl
