/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.EdilangPackage;
import io.thlaegler.edifact.edilang.NATSegment;
import io.thlaegler.edifact.edilang.NationalityDetail;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>NAT Segment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.NATSegmentImpl#getNationalityCodeQualifier <em>Nationality Code Qualifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.NATSegmentImpl#getNationalityDetails <em>Nationality Details</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NATSegmentImpl extends AbstractEdiSegmentImpl implements NATSegment
{
  /**
   * The default value of the '{@link #getNationalityCodeQualifier() <em>Nationality Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNationalityCodeQualifier()
   * @generated
   * @ordered
   */
  protected static final String NATIONALITY_CODE_QUALIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNationalityCodeQualifier() <em>Nationality Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNationalityCodeQualifier()
   * @generated
   * @ordered
   */
  protected String nationalityCodeQualifier = NATIONALITY_CODE_QUALIFIER_EDEFAULT;

  /**
   * The cached value of the '{@link #getNationalityDetails() <em>Nationality Details</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNationalityDetails()
   * @generated
   * @ordered
   */
  protected NationalityDetail nationalityDetails;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NATSegmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getNATSegment();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNationalityCodeQualifier()
  {
    return nationalityCodeQualifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNationalityCodeQualifier(String newNationalityCodeQualifier)
  {
    String oldNationalityCodeQualifier = nationalityCodeQualifier;
    nationalityCodeQualifier = newNationalityCodeQualifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.NAT_SEGMENT__NATIONALITY_CODE_QUALIFIER, oldNationalityCodeQualifier, nationalityCodeQualifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NationalityDetail getNationalityDetails()
  {
    return nationalityDetails;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNationalityDetails(NationalityDetail newNationalityDetails, NotificationChain msgs)
  {
    NationalityDetail oldNationalityDetails = nationalityDetails;
    nationalityDetails = newNationalityDetails;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EdilangPackage.NAT_SEGMENT__NATIONALITY_DETAILS, oldNationalityDetails, newNationalityDetails);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNationalityDetails(NationalityDetail newNationalityDetails)
  {
    if (newNationalityDetails != nationalityDetails)
    {
      NotificationChain msgs = null;
      if (nationalityDetails != null)
        msgs = ((InternalEObject)nationalityDetails).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EdilangPackage.NAT_SEGMENT__NATIONALITY_DETAILS, null, msgs);
      if (newNationalityDetails != null)
        msgs = ((InternalEObject)newNationalityDetails).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EdilangPackage.NAT_SEGMENT__NATIONALITY_DETAILS, null, msgs);
      msgs = basicSetNationalityDetails(newNationalityDetails, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.NAT_SEGMENT__NATIONALITY_DETAILS, newNationalityDetails, newNationalityDetails));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EdilangPackage.NAT_SEGMENT__NATIONALITY_DETAILS:
        return basicSetNationalityDetails(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.NAT_SEGMENT__NATIONALITY_CODE_QUALIFIER:
        return getNationalityCodeQualifier();
      case EdilangPackage.NAT_SEGMENT__NATIONALITY_DETAILS:
        return getNationalityDetails();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.NAT_SEGMENT__NATIONALITY_CODE_QUALIFIER:
        setNationalityCodeQualifier((String)newValue);
        return;
      case EdilangPackage.NAT_SEGMENT__NATIONALITY_DETAILS:
        setNationalityDetails((NationalityDetail)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.NAT_SEGMENT__NATIONALITY_CODE_QUALIFIER:
        setNationalityCodeQualifier(NATIONALITY_CODE_QUALIFIER_EDEFAULT);
        return;
      case EdilangPackage.NAT_SEGMENT__NATIONALITY_DETAILS:
        setNationalityDetails((NationalityDetail)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.NAT_SEGMENT__NATIONALITY_CODE_QUALIFIER:
        return NATIONALITY_CODE_QUALIFIER_EDEFAULT == null ? nationalityCodeQualifier != null : !NATIONALITY_CODE_QUALIFIER_EDEFAULT.equals(nationalityCodeQualifier);
      case EdilangPackage.NAT_SEGMENT__NATIONALITY_DETAILS:
        return nationalityDetails != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nationalityCodeQualifier: ");
    result.append(nationalityCodeQualifier);
    result.append(')');
    return result.toString();
  }

} //NATSegmentImpl
