/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.EdilangPackage;
import io.thlaegler.edifact.edilang.PercentageDetail;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Percentage Detail</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.PercentageDetailImpl#getPercentageTypeCodeQualifier <em>Percentage Type Code Qualifier</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.PercentageDetailImpl#getPercentage <em>Percentage</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.PercentageDetailImpl#getPercentageBasisIdentificationCode <em>Percentage Basis Identification Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.PercentageDetailImpl#getCodeListIdentificationCode <em>Code List Identification Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.PercentageDetailImpl#getCodeListResponsibleAgencyCode <em>Code List Responsible Agency Code</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PercentageDetailImpl extends MinimalEObjectImpl.Container implements PercentageDetail
{
  /**
   * The default value of the '{@link #getPercentageTypeCodeQualifier() <em>Percentage Type Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPercentageTypeCodeQualifier()
   * @generated
   * @ordered
   */
  protected static final String PERCENTAGE_TYPE_CODE_QUALIFIER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPercentageTypeCodeQualifier() <em>Percentage Type Code Qualifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPercentageTypeCodeQualifier()
   * @generated
   * @ordered
   */
  protected String percentageTypeCodeQualifier = PERCENTAGE_TYPE_CODE_QUALIFIER_EDEFAULT;

  /**
   * The default value of the '{@link #getPercentage() <em>Percentage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPercentage()
   * @generated
   * @ordered
   */
  protected static final String PERCENTAGE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPercentage() <em>Percentage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPercentage()
   * @generated
   * @ordered
   */
  protected String percentage = PERCENTAGE_EDEFAULT;

  /**
   * The default value of the '{@link #getPercentageBasisIdentificationCode() <em>Percentage Basis Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPercentageBasisIdentificationCode()
   * @generated
   * @ordered
   */
  protected static final String PERCENTAGE_BASIS_IDENTIFICATION_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPercentageBasisIdentificationCode() <em>Percentage Basis Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPercentageBasisIdentificationCode()
   * @generated
   * @ordered
   */
  protected String percentageBasisIdentificationCode = PERCENTAGE_BASIS_IDENTIFICATION_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListIdentificationCode() <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_IDENTIFICATION_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListIdentificationCode() <em>Code List Identification Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode()
   * @generated
   * @ordered
   */
  protected String codeListIdentificationCode = CODE_LIST_IDENTIFICATION_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListResponsibleAgencyCode() <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListResponsibleAgencyCode() <em>Code List Responsible Agency Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode()
   * @generated
   * @ordered
   */
  protected String codeListResponsibleAgencyCode = CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PercentageDetailImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getPercentageDetail();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPercentageTypeCodeQualifier()
  {
    return percentageTypeCodeQualifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPercentageTypeCodeQualifier(String newPercentageTypeCodeQualifier)
  {
    String oldPercentageTypeCodeQualifier = percentageTypeCodeQualifier;
    percentageTypeCodeQualifier = newPercentageTypeCodeQualifier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_TYPE_CODE_QUALIFIER, oldPercentageTypeCodeQualifier, percentageTypeCodeQualifier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPercentage()
  {
    return percentage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPercentage(String newPercentage)
  {
    String oldPercentage = percentage;
    percentage = newPercentage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE, oldPercentage, percentage));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPercentageBasisIdentificationCode()
  {
    return percentageBasisIdentificationCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPercentageBasisIdentificationCode(String newPercentageBasisIdentificationCode)
  {
    String oldPercentageBasisIdentificationCode = percentageBasisIdentificationCode;
    percentageBasisIdentificationCode = newPercentageBasisIdentificationCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_BASIS_IDENTIFICATION_CODE, oldPercentageBasisIdentificationCode, percentageBasisIdentificationCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListIdentificationCode()
  {
    return codeListIdentificationCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListIdentificationCode(String newCodeListIdentificationCode)
  {
    String oldCodeListIdentificationCode = codeListIdentificationCode;
    codeListIdentificationCode = newCodeListIdentificationCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_IDENTIFICATION_CODE, oldCodeListIdentificationCode, codeListIdentificationCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListResponsibleAgencyCode()
  {
    return codeListResponsibleAgencyCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListResponsibleAgencyCode(String newCodeListResponsibleAgencyCode)
  {
    String oldCodeListResponsibleAgencyCode = codeListResponsibleAgencyCode;
    codeListResponsibleAgencyCode = newCodeListResponsibleAgencyCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE, oldCodeListResponsibleAgencyCode, codeListResponsibleAgencyCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_TYPE_CODE_QUALIFIER:
        return getPercentageTypeCodeQualifier();
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE:
        return getPercentage();
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_BASIS_IDENTIFICATION_CODE:
        return getPercentageBasisIdentificationCode();
      case EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_IDENTIFICATION_CODE:
        return getCodeListIdentificationCode();
      case EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        return getCodeListResponsibleAgencyCode();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_TYPE_CODE_QUALIFIER:
        setPercentageTypeCodeQualifier((String)newValue);
        return;
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE:
        setPercentage((String)newValue);
        return;
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_BASIS_IDENTIFICATION_CODE:
        setPercentageBasisIdentificationCode((String)newValue);
        return;
      case EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_IDENTIFICATION_CODE:
        setCodeListIdentificationCode((String)newValue);
        return;
      case EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        setCodeListResponsibleAgencyCode((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_TYPE_CODE_QUALIFIER:
        setPercentageTypeCodeQualifier(PERCENTAGE_TYPE_CODE_QUALIFIER_EDEFAULT);
        return;
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE:
        setPercentage(PERCENTAGE_EDEFAULT);
        return;
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_BASIS_IDENTIFICATION_CODE:
        setPercentageBasisIdentificationCode(PERCENTAGE_BASIS_IDENTIFICATION_CODE_EDEFAULT);
        return;
      case EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_IDENTIFICATION_CODE:
        setCodeListIdentificationCode(CODE_LIST_IDENTIFICATION_CODE_EDEFAULT);
        return;
      case EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        setCodeListResponsibleAgencyCode(CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_TYPE_CODE_QUALIFIER:
        return PERCENTAGE_TYPE_CODE_QUALIFIER_EDEFAULT == null ? percentageTypeCodeQualifier != null : !PERCENTAGE_TYPE_CODE_QUALIFIER_EDEFAULT.equals(percentageTypeCodeQualifier);
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE:
        return PERCENTAGE_EDEFAULT == null ? percentage != null : !PERCENTAGE_EDEFAULT.equals(percentage);
      case EdilangPackage.PERCENTAGE_DETAIL__PERCENTAGE_BASIS_IDENTIFICATION_CODE:
        return PERCENTAGE_BASIS_IDENTIFICATION_CODE_EDEFAULT == null ? percentageBasisIdentificationCode != null : !PERCENTAGE_BASIS_IDENTIFICATION_CODE_EDEFAULT.equals(percentageBasisIdentificationCode);
      case EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_IDENTIFICATION_CODE:
        return CODE_LIST_IDENTIFICATION_CODE_EDEFAULT == null ? codeListIdentificationCode != null : !CODE_LIST_IDENTIFICATION_CODE_EDEFAULT.equals(codeListIdentificationCode);
      case EdilangPackage.PERCENTAGE_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE:
        return CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT == null ? codeListResponsibleAgencyCode != null : !CODE_LIST_RESPONSIBLE_AGENCY_CODE_EDEFAULT.equals(codeListResponsibleAgencyCode);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (percentageTypeCodeQualifier: ");
    result.append(percentageTypeCodeQualifier);
    result.append(", percentage: ");
    result.append(percentage);
    result.append(", percentageBasisIdentificationCode: ");
    result.append(percentageBasisIdentificationCode);
    result.append(", codeListIdentificationCode: ");
    result.append(codeListIdentificationCode);
    result.append(", codeListResponsibleAgencyCode: ");
    result.append(codeListResponsibleAgencyCode);
    result.append(')');
    return result.toString();
  }

} //PercentageDetailImpl
