/**
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.edilang.impl;

import io.thlaegler.edifact.edilang.EdilangPackage;
import io.thlaegler.edifact.edilang.TaxDetail;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tax Detail</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.TaxDetailImpl#getTaxRateDescriptionCode <em>Tax Rate Description Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.TaxDetailImpl#getCodeListIdentificationCode1 <em>Code List Identification Code1</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.TaxDetailImpl#getCodeListResponsibleAgencyCode1 <em>Code List Responsible Agency Code1</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.TaxDetailImpl#getTaxRateDescription <em>Tax Rate Description</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.TaxDetailImpl#getTaxRateBasisCode <em>Tax Rate Basis Code</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.TaxDetailImpl#getCodeListIdentificationCode2 <em>Code List Identification Code2</em>}</li>
 *   <li>{@link io.thlaegler.edifact.edilang.impl.TaxDetailImpl#getCodeListResponsibleAgencyCode2 <em>Code List Responsible Agency Code2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TaxDetailImpl extends AbstractEdiFunctionImpl implements TaxDetail
{
  /**
   * The default value of the '{@link #getTaxRateDescriptionCode() <em>Tax Rate Description Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaxRateDescriptionCode()
   * @generated
   * @ordered
   */
  protected static final String TAX_RATE_DESCRIPTION_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTaxRateDescriptionCode() <em>Tax Rate Description Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaxRateDescriptionCode()
   * @generated
   * @ordered
   */
  protected String taxRateDescriptionCode = TAX_RATE_DESCRIPTION_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListIdentificationCode1() <em>Code List Identification Code1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode1()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_IDENTIFICATION_CODE1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListIdentificationCode1() <em>Code List Identification Code1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode1()
   * @generated
   * @ordered
   */
  protected String codeListIdentificationCode1 = CODE_LIST_IDENTIFICATION_CODE1_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListResponsibleAgencyCode1() <em>Code List Responsible Agency Code1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode1()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_RESPONSIBLE_AGENCY_CODE1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListResponsibleAgencyCode1() <em>Code List Responsible Agency Code1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode1()
   * @generated
   * @ordered
   */
  protected String codeListResponsibleAgencyCode1 = CODE_LIST_RESPONSIBLE_AGENCY_CODE1_EDEFAULT;

  /**
   * The default value of the '{@link #getTaxRateDescription() <em>Tax Rate Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaxRateDescription()
   * @generated
   * @ordered
   */
  protected static final String TAX_RATE_DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTaxRateDescription() <em>Tax Rate Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaxRateDescription()
   * @generated
   * @ordered
   */
  protected String taxRateDescription = TAX_RATE_DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getTaxRateBasisCode() <em>Tax Rate Basis Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaxRateBasisCode()
   * @generated
   * @ordered
   */
  protected static final String TAX_RATE_BASIS_CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTaxRateBasisCode() <em>Tax Rate Basis Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaxRateBasisCode()
   * @generated
   * @ordered
   */
  protected String taxRateBasisCode = TAX_RATE_BASIS_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListIdentificationCode2() <em>Code List Identification Code2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode2()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_IDENTIFICATION_CODE2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListIdentificationCode2() <em>Code List Identification Code2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListIdentificationCode2()
   * @generated
   * @ordered
   */
  protected String codeListIdentificationCode2 = CODE_LIST_IDENTIFICATION_CODE2_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeListResponsibleAgencyCode2() <em>Code List Responsible Agency Code2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode2()
   * @generated
   * @ordered
   */
  protected static final String CODE_LIST_RESPONSIBLE_AGENCY_CODE2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeListResponsibleAgencyCode2() <em>Code List Responsible Agency Code2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeListResponsibleAgencyCode2()
   * @generated
   * @ordered
   */
  protected String codeListResponsibleAgencyCode2 = CODE_LIST_RESPONSIBLE_AGENCY_CODE2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TaxDetailImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdilangPackage.eINSTANCE.getTaxDetail();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTaxRateDescriptionCode()
  {
    return taxRateDescriptionCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTaxRateDescriptionCode(String newTaxRateDescriptionCode)
  {
    String oldTaxRateDescriptionCode = taxRateDescriptionCode;
    taxRateDescriptionCode = newTaxRateDescriptionCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION_CODE, oldTaxRateDescriptionCode, taxRateDescriptionCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListIdentificationCode1()
  {
    return codeListIdentificationCode1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListIdentificationCode1(String newCodeListIdentificationCode1)
  {
    String oldCodeListIdentificationCode1 = codeListIdentificationCode1;
    codeListIdentificationCode1 = newCodeListIdentificationCode1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE1, oldCodeListIdentificationCode1, codeListIdentificationCode1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListResponsibleAgencyCode1()
  {
    return codeListResponsibleAgencyCode1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListResponsibleAgencyCode1(String newCodeListResponsibleAgencyCode1)
  {
    String oldCodeListResponsibleAgencyCode1 = codeListResponsibleAgencyCode1;
    codeListResponsibleAgencyCode1 = newCodeListResponsibleAgencyCode1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE1, oldCodeListResponsibleAgencyCode1, codeListResponsibleAgencyCode1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTaxRateDescription()
  {
    return taxRateDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTaxRateDescription(String newTaxRateDescription)
  {
    String oldTaxRateDescription = taxRateDescription;
    taxRateDescription = newTaxRateDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION, oldTaxRateDescription, taxRateDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTaxRateBasisCode()
  {
    return taxRateBasisCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTaxRateBasisCode(String newTaxRateBasisCode)
  {
    String oldTaxRateBasisCode = taxRateBasisCode;
    taxRateBasisCode = newTaxRateBasisCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.TAX_DETAIL__TAX_RATE_BASIS_CODE, oldTaxRateBasisCode, taxRateBasisCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListIdentificationCode2()
  {
    return codeListIdentificationCode2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListIdentificationCode2(String newCodeListIdentificationCode2)
  {
    String oldCodeListIdentificationCode2 = codeListIdentificationCode2;
    codeListIdentificationCode2 = newCodeListIdentificationCode2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE2, oldCodeListIdentificationCode2, codeListIdentificationCode2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeListResponsibleAgencyCode2()
  {
    return codeListResponsibleAgencyCode2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeListResponsibleAgencyCode2(String newCodeListResponsibleAgencyCode2)
  {
    String oldCodeListResponsibleAgencyCode2 = codeListResponsibleAgencyCode2;
    codeListResponsibleAgencyCode2 = newCodeListResponsibleAgencyCode2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE2, oldCodeListResponsibleAgencyCode2, codeListResponsibleAgencyCode2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION_CODE:
        return getTaxRateDescriptionCode();
      case EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE1:
        return getCodeListIdentificationCode1();
      case EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE1:
        return getCodeListResponsibleAgencyCode1();
      case EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION:
        return getTaxRateDescription();
      case EdilangPackage.TAX_DETAIL__TAX_RATE_BASIS_CODE:
        return getTaxRateBasisCode();
      case EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE2:
        return getCodeListIdentificationCode2();
      case EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE2:
        return getCodeListResponsibleAgencyCode2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION_CODE:
        setTaxRateDescriptionCode((String)newValue);
        return;
      case EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE1:
        setCodeListIdentificationCode1((String)newValue);
        return;
      case EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE1:
        setCodeListResponsibleAgencyCode1((String)newValue);
        return;
      case EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION:
        setTaxRateDescription((String)newValue);
        return;
      case EdilangPackage.TAX_DETAIL__TAX_RATE_BASIS_CODE:
        setTaxRateBasisCode((String)newValue);
        return;
      case EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE2:
        setCodeListIdentificationCode2((String)newValue);
        return;
      case EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE2:
        setCodeListResponsibleAgencyCode2((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION_CODE:
        setTaxRateDescriptionCode(TAX_RATE_DESCRIPTION_CODE_EDEFAULT);
        return;
      case EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE1:
        setCodeListIdentificationCode1(CODE_LIST_IDENTIFICATION_CODE1_EDEFAULT);
        return;
      case EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE1:
        setCodeListResponsibleAgencyCode1(CODE_LIST_RESPONSIBLE_AGENCY_CODE1_EDEFAULT);
        return;
      case EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION:
        setTaxRateDescription(TAX_RATE_DESCRIPTION_EDEFAULT);
        return;
      case EdilangPackage.TAX_DETAIL__TAX_RATE_BASIS_CODE:
        setTaxRateBasisCode(TAX_RATE_BASIS_CODE_EDEFAULT);
        return;
      case EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE2:
        setCodeListIdentificationCode2(CODE_LIST_IDENTIFICATION_CODE2_EDEFAULT);
        return;
      case EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE2:
        setCodeListResponsibleAgencyCode2(CODE_LIST_RESPONSIBLE_AGENCY_CODE2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION_CODE:
        return TAX_RATE_DESCRIPTION_CODE_EDEFAULT == null ? taxRateDescriptionCode != null : !TAX_RATE_DESCRIPTION_CODE_EDEFAULT.equals(taxRateDescriptionCode);
      case EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE1:
        return CODE_LIST_IDENTIFICATION_CODE1_EDEFAULT == null ? codeListIdentificationCode1 != null : !CODE_LIST_IDENTIFICATION_CODE1_EDEFAULT.equals(codeListIdentificationCode1);
      case EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE1:
        return CODE_LIST_RESPONSIBLE_AGENCY_CODE1_EDEFAULT == null ? codeListResponsibleAgencyCode1 != null : !CODE_LIST_RESPONSIBLE_AGENCY_CODE1_EDEFAULT.equals(codeListResponsibleAgencyCode1);
      case EdilangPackage.TAX_DETAIL__TAX_RATE_DESCRIPTION:
        return TAX_RATE_DESCRIPTION_EDEFAULT == null ? taxRateDescription != null : !TAX_RATE_DESCRIPTION_EDEFAULT.equals(taxRateDescription);
      case EdilangPackage.TAX_DETAIL__TAX_RATE_BASIS_CODE:
        return TAX_RATE_BASIS_CODE_EDEFAULT == null ? taxRateBasisCode != null : !TAX_RATE_BASIS_CODE_EDEFAULT.equals(taxRateBasisCode);
      case EdilangPackage.TAX_DETAIL__CODE_LIST_IDENTIFICATION_CODE2:
        return CODE_LIST_IDENTIFICATION_CODE2_EDEFAULT == null ? codeListIdentificationCode2 != null : !CODE_LIST_IDENTIFICATION_CODE2_EDEFAULT.equals(codeListIdentificationCode2);
      case EdilangPackage.TAX_DETAIL__CODE_LIST_RESPONSIBLE_AGENCY_CODE2:
        return CODE_LIST_RESPONSIBLE_AGENCY_CODE2_EDEFAULT == null ? codeListResponsibleAgencyCode2 != null : !CODE_LIST_RESPONSIBLE_AGENCY_CODE2_EDEFAULT.equals(codeListResponsibleAgencyCode2);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (taxRateDescriptionCode: ");
    result.append(taxRateDescriptionCode);
    result.append(", codeListIdentificationCode1: ");
    result.append(codeListIdentificationCode1);
    result.append(", codeListResponsibleAgencyCode1: ");
    result.append(codeListResponsibleAgencyCode1);
    result.append(", taxRateDescription: ");
    result.append(taxRateDescription);
    result.append(", taxRateBasisCode: ");
    result.append(taxRateBasisCode);
    result.append(", codeListIdentificationCode2: ");
    result.append(codeListIdentificationCode2);
    result.append(", codeListResponsibleAgencyCode2: ");
    result.append(codeListResponsibleAgencyCode2);
    result.append(')');
    return result.toString();
  }

} //TaxDetailImpl
