/*
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEdilangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(io.thlaegler.edifact.edilang.EdilangPackage.eINSTANCE);
		return result;
	}
}
