/*
 * generated by Xtext 2.26.0
 */
package io.thlaegler.edifact.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import io.thlaegler.edifact.EdilangRuntimeModule;
import io.thlaegler.edifact.EdilangStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EdilangIdeSetup extends EdilangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EdilangRuntimeModule(), new EdilangIdeModule()));
	}
	
}
